import os, json, random, logging, urllib.request
from datetime import datetime

TOKEN   = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
log = logging.getLogger(__name__)

# ============================================================
# 300 KANJI N4
# ============================================================
KANJI = [
    ("悲","かな/ひ","sedih","悲しい映画を見て泣いた。","Kanashii eiga o mite naita.","Menonton film sedih sampai menangis."),
    ("暑","あつ/しょ","panas (cuaca)","今日は本当に暑いですね。","Kyou wa hontou ni atsui desu ne.","Hari ini benar-benar panas ya."),
    ("寒","さむ/かん","dingin (cuaca)","冬は寒くて大変です。","Fuyu wa samukute taihen desu.","Musim dingin dingin sekali."),
    ("春","はる/しゅん","musim semi","春になると花が咲きます。","Haru ni naru to hana ga sakimasu.","Ketika musim semi tiba bunga mekar."),
    ("夏","なつ/か","musim panas","夏休みに海へ行きます。","Natsuyasumi ni umi e ikimasu.","Pergi ke laut saat liburan musim panas."),
    ("秋","あき/しゅう","musim gugur","秋は紅葉がきれいです。","Aki wa kouyou ga kirei desu.","Musim gugur dedaunannya indah."),
    ("冬","ふゆ/とう","musim dingin","冬はスキーが楽しい。","Fuyu wa sukii ga tanoshii.","Musim dingin ski menyenangkan."),
    ("朝","あさ/ちょう","pagi","毎朝早く起きます。","Maiasa hayaku okimasu.","Bangun pagi setiap hari."),
    ("昼","ひる/ちゅう","siang","昼ごはんは何を食べますか。","Hirugohan wa nani o tabemasu ka.","Makan siang apa?"),
    ("夜","よる/や","malam","夜遅くまで勉強した。","Yoru osoku made benkyou shita.","Belajar sampai larut malam."),
    ("毎","まい","setiap","毎日日本語を練習します。","Mainichi nihongo o renshuu shimasu.","Berlatih bahasa Jepang setiap hari."),
    ("週","しゅう","minggu","来週テストがあります。","Raishuu tesuto ga arimasu.","Minggu depan ada ujian."),
    ("間","あいだ/かん","antara/selama","授業の間は静かにする。","Jugyou no aida wa shizuka ni suru.","Diam selama pelajaran."),
    ("前","まえ/ぜん","depan/sebelum","食事の前に手を洗う。","Shokuji no mae ni te o arau.","Cuci tangan sebelum makan."),
    ("後","あと/ご","belakang/setelah","授業の後で友達と話した。","Jugyou no ato de tomodachi to hanashita.","Berbicara dengan teman setelah kelas."),
    ("次","つぎ/じ","berikutnya","次の駅で降ります。","Tsugi no eki de orimasu.","Turun di stasiun berikutnya."),
    ("同","おな/どう","sama","同じ意見です。","Onaji iken desu.","Pendapat yang sama."),
    ("多","おお/た","banyak","宿題が多すぎる。","Shukudai ga oosugiru.","PR-nya terlalu banyak."),
    ("少","すこ/しょう","sedikit","少し待ってください。","Sukoshi matte kudasai.","Tolong tunggu sebentar."),
    ("長","なが/ちょう","panjang/lama","長い時間がかかった。","Nagai jikan ga kakatta.","Membutuhkan waktu yang lama."),
    ("短","みじか/たん","pendek/singkat","この映画は短い。","Kono eiga wa mijikai.","Film ini pendek."),
    ("高","たか/こう","tinggi/mahal","山が高い。","Yama ga takai.","Gunungnya tinggi."),
    ("低","ひく/てい","rendah","声が低い人です。","Koe ga hikui hito desu.","Orang yang suaranya rendah."),
    ("広","ひろ/こう","luas","公園が広いです。","Kouen ga hiroi desu.","Tamannya luas."),
    ("狭","せま/きょう","sempit","部屋が狭い。","Heya ga semai.","Kamarnya sempit."),
    ("強","つよ/きょう","kuat","強い風が吹いている。","Tsuyoi kaze ga fuite iru.","Angin kencang berhembus."),
    ("弱","よわ/じゃく","lemah","体が弱い人です。","Karada ga yowai hito desu.","Orang yang badannya lemah."),
    ("早","はや/そう","cepat/awal","早く起きてください。","Hayaku okite kudasai.","Tolong bangun cepat."),
    ("遅","おそ/ち","lambat/terlambat","電車が遅れています。","Densha ga okurete imasu.","Keretanya terlambat."),
    ("新","あたら/しん","baru","新しい仕事を始めた。","Atarashii shigoto o hajimeta.","Memulai pekerjaan baru."),
    ("古","ふる/こ","lama/tua","古い建物を修理した。","Furui tatemono o shuurishita.","Memperbaiki bangunan tua."),
    ("若","わか/じゃく","muda","若い人が増えている。","Wakai hito ga fuete iru.","Orang muda semakin bertambah."),
    ("太","ふと/た","gemuk/tebal","少し太ってしまった。","Sukoshi futotte shimatta.","Sedikit gemuk."),
    ("細","ほそ/さい","tipis/langsing","細い道を歩いた。","Hosoi michi o aruita.","Berjalan di jalan sempit."),
    ("重","おも/じゅう","berat","荷物が重い。","Nimotsu ga omoi.","Barang bawaannya berat."),
    ("軽","かる/けい","ringan","このバッグは軽い。","Kono baggu wa karui.","Tas ini ringan."),
    ("近","ちか/きん","dekat","駅が近くて便利です。","Eki ga chikakute benri desu.","Stasiunnya dekat, praktis."),
    ("遠","とお/えん","jauh","学校が家から遠い。","Gakkou ga ie kara tooi.","Sekolah jauh dari rumah."),
    ("明","あか/めい","terang/jelas","明るい部屋が好きです。","Akarui heya ga suki desu.","Suka kamar yang terang."),
    ("暗","くら/あん","gelap","急に暗くなった。","Kyuu ni kuraku natta.","Tiba-tiba menjadi gelap."),
    ("正","ただ/せい","benar/tepat","正しい答えを選んで。","Tadashii kotae o erande.","Pilih jawaban yang benar."),
    ("親","おや/しん","orang tua/akrab","親切にしてくれてありがとう。","Shinsetsu ni shite kurete arigatou.","Terima kasih sudah baik hati."),
    ("友","とも/ゆう","teman","友達と映画を見た。","Tomodachi to eiga o mita.","Menonton film bersama teman."),
    ("兄","あに/けい","kakak laki-laki","兄は医者です。","Ani wa isha desu.","Kakak laki-laki saya dokter."),
    ("姉","あね/し","kakak perempuan","姉は料理が上手です。","Ane wa ryouri ga jouzu desu.","Kakak perempuan pandai memasak."),
    ("弟","おとうと/てい","adik laki-laki","弟と一緒に遊んだ。","Otouto to issho ni asonda.","Bermain bersama adik laki-laki."),
    ("妹","いもうと/まい","adik perempuan","妹は学生です。","Imouto wa gakusei desu.","Adik perempuan saya pelajar."),
    ("夫","おっと/ふ","suami","夫は会社員です。","Otto wa kaishain desu.","Suami saya karyawan."),
    ("妻","つま/さい","istri","妻と一緒に料理します。","Tsuma to issho ni ryouri shimasu.","Memasak bersama istri."),
    ("体","からだ/たい","tubuh","体を大切にしてください。","Karada o taisetsu ni shite kudasai.","Tolong jaga tubuhmu."),
    ("頭","あたま/ず","kepala","頭が痛い。","Atama ga itai.","Kepala sakit."),
    ("顔","かお/がん","wajah","彼女は顔が可愛い。","Kanojo wa kao ga kawaii.","Wajahnya cantik."),
    ("声","こえ/せい","suara","大きな声で話してください。","Ookina koe de hanashite kudasai.","Tolong bicara dengan suara keras."),
    ("心","こころ/しん","hati/perasaan","心が温かい人です。","Kokoro ga atatakai hito desu.","Orang yang hatinya hangat."),
    ("力","ちから/りょく","kekuatan","力を合わせて頑張ろう。","Chikara o awasete ganbarou.","Mari berjuang dengan menyatukan kekuatan."),
    ("思","おも/し","berpikir/merasa","そう思います。","Sou omoimasu.","Saya pikir begitu."),
    ("考","かんが/こう","memikirkan","よく考えてから決める。","Yoku kangaete kara kimeru.","Memutuskan setelah berpikir matang."),
    ("感","かん","merasakan","感動しました。","Kandou shimashita.","Saya terharu."),
    ("言","い/げん","berkata","何も言わないでください。","Nani mo iwanaide kudasai.","Tolong jangan berkata apa-apa."),
    ("語","ご","bahasa/kata","日本語を勉強しています。","Nihongo o benkyou shite imasu.","Sedang belajar bahasa Jepang."),
    ("教","おし/きょう","mengajar","先生が数学を教えた。","Sensei ga suugaku o oshieta.","Guru mengajarkan matematika."),
    ("習","なら/しゅう","belajar/berlatih","ピアノを習っています。","Piano o naratte imasu.","Sedang belajar piano."),
    ("答","こた/とう","menjawab","質問に答えてください。","Shitsumon ni kotaete kudasai.","Tolong jawab pertanyaannya."),
    ("使","つか/し","menggunakan","辞書を使ってください。","Jisho o tsukatte kudasai.","Tolong gunakan kamus."),
    ("作","つく/さく","membuat","料理を作りました。","Ryouri o tsukurimashita.","Membuat masakan."),
    ("売","う/ばい","menjual","この店で野菜を売っている。","Kono mise de yasai o utte iru.","Toko ini menjual sayuran."),
    ("買","か/ばい","membeli","新しい本を買った。","Atarashii hon o katta.","Membeli buku baru."),
    ("借","か/しゃく","meminjam","図書館で本を借りた。","Toshokan de hon o karita.","Meminjam buku di perpustakaan."),
    ("貸","か/たい","meminjamkan","友達に傘を貸した。","Tomodachi ni kasa o kashita.","Meminjamkan payung kepada teman."),
    ("送","おく/そう","mengirim","メールを送りました。","Meeru o okurimashita.","Mengirim email."),
    ("着","き/ちゃく","tiba/memakai","駅に着きました。","Eki ni tsukimashita.","Sudah tiba di stasiun."),
    ("起","お/き","bangun/terjadi","事故が起きた。","Jiko ga okita.","Kecelakaan terjadi."),
    ("寝","ね/しん","tidur","早く寝てください。","Hayaku nete kudasai.","Tolong tidur cepat."),
    ("立","た/りつ","berdiri","立ってください。","Tatte kudasai.","Tolong berdiri."),
    ("座","すわ/ざ","duduk","どうぞ座ってください。","Douzo suwatte kudasai.","Silakan duduk."),
    ("走","はし/そう","berlari","公園を走った。","Kouen o hashitta.","Berlari di taman."),
    ("泳","およ/えい","berenang","海で泳いだ。","Umi de oyoida.","Berenang di laut."),
    ("飛","と/ひ","terbang","鳥が空を飛んでいる。","Tori ga sora o tonde iru.","Burung terbang di langit."),
    ("乗","の/じょう","menaiki","バスに乗ります。","Basu ni norimasu.","Naik bus."),
    ("降","お/こう","turun/hujan","電車を降りた。","Densha o orita.","Turun dari kereta."),
    ("開","あ/かい","membuka","窓を開けてください。","Mado o akete kudasai.","Tolong buka jendelanya."),
    ("閉","し/へい","menutup","ドアを閉めてください。","Doa o shimete kudasai.","Tolong tutup pintunya."),
    ("始","はじ/し","memulai","授業が始まります。","Jugyou ga hajimarimasu.","Pelajaran dimulai."),
    ("終","お/しゅう","mengakhiri","仕事が終わった。","Shigoto ga owatta.","Pekerjaan selesai."),
    ("止","と/し","berhenti","車が止まった。","Kuruma ga tomatta.","Mobil berhenti."),
    ("待","ま/たい","menunggu","少し待ってください。","Sukoshi matte kudasai.","Tolong tunggu sebentar."),
    ("会","あ/かい","bertemu","友達に会いました。","Tomodachi ni aimashita.","Bertemu dengan teman."),
    ("帰","かえ/き","pulang","家に帰ります。","Ie ni kaerimasu.","Pulang ke rumah."),
    ("出","で/しゅつ","keluar","家を出ました。","Ie o demashita.","Keluar dari rumah."),
    ("入","はい/にゅう","masuk","部屋に入ってください。","Heya ni haitte kudasai.","Tolong masuk ke kamar."),
    ("持","も/じ","membawa/memegang","傘を持って行く。","Kasa o motte iku.","Membawa payung pergi."),
    ("置","お/ち","meletakkan","机の上に置いた。","Tsukue no ue ni oita.","Meletakkan di atas meja."),
    ("切","き/せつ","memotong","紙を切った。","Kami o kitta.","Memotong kertas."),
    ("洗","あら/せん","mencuci","手を洗ってください。","Te o aratte kudasai.","Tolong cuci tangan."),
    ("脱","ぬ/だつ","melepas (pakaian)","靴を脱いでください。","Kutsu o nuide kudasai.","Tolong lepas sepatunya."),
    ("歌","うた/か","bernyanyi/lagu","歌を歌った。","Uta o utatta.","Menyanyikan lagu."),
    ("踊","おど/よう","menari","ダンスを踊った。","Dansu o odotta.","Menari dansa."),
    ("泣","な/きゅう","menangis","映画を見て泣いた。","Eiga o mite naita.","Menangis menonton film."),
    ("笑","わら/しょう","tertawa/senyum","友達と笑った。","Tomodachi to waratta.","Tertawa bersama teman."),
    ("怒","おこ/ど","marah","先生が怒った。","Sensei ga okotta.","Guru marah."),
    ("喜","よろこ/き","gembira","合格して喜んだ。","Goukaku shite yorokonda.","Gembira karena lulus."),
    ("忘","わす/ぼう","melupakan","名前を忘れた。","Namae o wasureta.","Lupa namanya."),
    ("覚","おぼ/かく","mengingat/menghafal","単語を覚えた。","Tango o oboeta.","Menghafal kosakata."),
    ("決","き/けつ","memutuskan","旅行の日程を決めた。","Ryokou no nittei o kimeta.","Memutuskan jadwal perjalanan."),
    ("選","えら/せん","memilih","プレゼントを選んだ。","Purezento o eranda.","Memilih hadiah."),
    ("変","か/へん","berubah","考えが変わった。","Kangae ga kawatta.","Pikiran berubah."),
    ("増","ふ/ぞう","bertambah","仕事が増えた。","Shigoto ga fueta.","Pekerjaan bertambah."),
    ("集","あつ/しゅう","mengumpulkan","情報を集めた。","Jouhou o atsumeta.","Mengumpulkan informasi."),
    ("助","たす/じょ","membantu","友達を助けた。","Tomodachi o tasuketa.","Membantu teman."),
    ("頼","たの/らい","meminta/mengandalkan","友達に頼んだ。","Tomodachi ni tanonda.","Meminta tolong teman."),
    ("信","しん","mempercayai","友達を信じる。","Tomodachi o shinjiru.","Mempercayai teman."),
    ("守","まも/しゅ","menjaga","ルールを守ってください。","Ruuru o mamotte kudasai.","Tolong patuhi aturan."),
    ("払","はら/ふつ","membayar","料金を払った。","Ryoukin o haratta.","Membayar biaya."),
    ("返","かえ/へん","mengembalikan","本を返した。","Hon o kaeshita.","Mengembalikan buku."),
    ("押","お/おう","mendorong","ボタンを押してください。","Botan o oshite kudasai.","Tolong tekan tombolnya."),
    ("引","ひ/いん","menarik","ドアを引いてください。","Doa o hiite kudasai.","Tolong tarik pintunya."),
    ("回","まわ/かい","berputar/kali","3回練習した。","Sankai renshuu shita.","Berlatih 3 kali."),
    ("落","お/らく","jatuh","財布が落ちた。","Saifu ga ochita.","Dompet jatuh."),
    ("建","た/けん","membangun","家を建てた。","Ie o tateta.","Membangun rumah."),
    ("住","す/じゅう","tinggal","東京に住んでいる。","Toukyou ni sunde iru.","Tinggal di Tokyo."),
    ("旅","たび/りょ","perjalanan","旅行が好きです。","Ryokou ga suki desu.","Suka berwisata."),
    ("泊","と/はく","menginap","ホテルに泊まった。","Hoteru ni tomatta.","Menginap di hotel."),
    ("遊","あそ/ゆう","bermain","公園で遊んだ。","Kouen de asonda.","Bermain di taman."),
    ("休","やす/きゅう","beristirahat","今日は休みます。","Kyou wa yasumimasu.","Hari ini istirahat."),
    ("働","はたら/どう","bekerja","毎日働いています。","Mainichi hataraite imasu.","Bekerja setiap hari."),
    ("練","れん","berlatih","毎日練習する。","Mainichi renshuu suru.","Berlatih setiap hari."),
    ("合","あ/ごう","cocok/lulus","試験に合格した。","Shiken ni goukaku shita.","Lulus ujian."),
    ("負","ま/ふ","kalah","試合に負けた。","Shiai ni maketa.","Kalah dalam pertandingan."),
    ("勝","か/しょう","menang","試合に勝った。","Shiai ni katta.","Menang dalam pertandingan."),
    ("似","に/じ","mirip","兄に似ています。","Ani ni nite imasu.","Mirip dengan kakak."),
    ("違","ちが/い","berbeda/salah","意見が違う。","Iken ga chigau.","Pendapat berbeda."),
    ("困","こま/こん","bingung/susah","この問題は困った。","Kono mondai wa komatta.","Soal ini membingungkan."),
    ("急","いそ/きゅう","tergesa-gesa","急いでください。","Isoide kudasai.","Tolong bergegas."),
    ("続","つづ/ぞく","melanjutkan","練習を続けよう。","Renshuu o tsuzukeyou.","Mari lanjutkan latihan."),
    ("渡","わた/と","menyeberangi/memberikan","橋を渡った。","Hashi o watatta.","Menyeberangi jembatan."),
    ("曲","ま/きょく","membelok/lagu","角を曲がった。","Kado o magatta.","Membelok di tikungan."),
    ("転","ころ/てん","jatuh/berputar","自転車で転んだ。","Jitensha de koronda.","Jatuh dari sepeda."),
    ("知","し/ち","mengetahui","この場所を知っている。","Kono basho o shitte iru.","Mengetahui tempat ini."),
    ("分","わか/ぶん","mengerti/membagi","意味が分かった。","Imi ga wakatta.","Mengerti artinya."),
    ("問","と/もん","bertanya/masalah","問題を解いた。","Mondai o toita.","Memecahkan soal."),
    ("受","う/じゅ","menerima","試験を受けた。","Shiken o uketa.","Mengikuti ujian."),
    ("注","そそ/ちゅう","menuang/perhatian","注意してください。","Chuui shite kudasai.","Tolong perhatikan."),
    ("調","しら/ちょう","menyelidiki","インターネットで調べた。","Intaanetto de shirabeta.","Mencari tahu di internet."),
    ("比","くら/ひ","membandingkan","二つを比べた。","Futatsu o kurabeta.","Membandingkan keduanya."),
    ("減","へ/げん","berkurang","体重が減った。","Taijuu ga hetta.","Berat badan berkurang."),
    ("取","と/しゅ","mengambil","メモを取った。","Memo o totta.","Mencatat."),
    ("役","やく","peran/berguna","役に立つ情報です。","Yaku ni tatsu jouhou desu.","Ini informasi yang berguna."),
    ("礼","れい","sopan santun/terima kasih","お礼を言いたい。","Orei o iitai.","Ingin mengucapkan terima kasih."),
    ("数","かず/すう","angka/jumlah","数学が得意です。","Suugaku ga tokui desu.","Saya pandai matematika."),
    ("点","てん","poin/titik","テストで100点を取った。","Tesuto de hyakuten o totta.","Mendapat nilai 100 di tes."),
    ("度","たび/ど","derajat/kali","何度も練習した。","Nando mo renshuu shita.","Berlatih berkali-kali."),
    ("番","ばん","nomor urut/giliran","1番を選んでください。","Ichiban o erande kudasai.","Tolong pilih nomor 1."),
    ("号","ごう","nomor/sinyal","何号室ですか。","Nangou-shitsu desuka.","Kamar nomor berapa?"),
    ("半","はん","setengah","3時半に会いましょう。","Sanji-han ni aimashou.","Mari bertemu pukul 3 setengah."),
    ("以","い","dengan/sejak","以前より上手になった。","Izen yori jouzu ni natta.","Sudah lebih mahir dari sebelumnya."),
    ("予","あらかじ/よ","sebelumnya/rencana","予定を確認してください。","Yotei o kakunin shite kudasai.","Tolong cek jadwalnya."),
    ("約","やく","janji/kira-kira","約束を守る。","Yakusoku o mamoru.","Menepati janji."),
    ("計","はか/けい","menghitung/rencana","時間を計った。","Jikan o hakatta.","Mengukur waktu."),
    ("算","さん","menghitung","計算が得意です。","Keisan ga tokui desu.","Pandai berhitung."),
    ("料","りょう","biaya/bahan","料金を払った。","Ryoukin o haratta.","Membayar biaya."),
    ("費","つい/ひ","pengeluaran/biaya","生活費が高い。","Seikatsuhi ga takai.","Biaya hidup mahal."),
    ("産","う/さん","melahirkan/produk","地元の産物を大切にする。","Jimoto no sanbutsu o taisetsu ni suru.","Menghargai produk lokal."),
    ("商","しょう","berdagang/komersial","商品の値段を確認する。","Shouhin no nedan o kakunin suru.","Mengecek harga produk."),
    ("品","しな/ひん","barang/produk","品質がいい商品です。","Hinshitsu ga ii shouhin desu.","Ini produk berkualitas baik."),
    ("店","みせ/てん","toko","あの店は有名です。","Ano mise wa yuumei desu.","Toko itu terkenal."),
    ("屋","や/おく","toko/atap","パン屋でパンを買った。","Pan-ya de pan o katta.","Membeli roti di toko roti."),
    ("市","いち/し","pasar/kota","市場で野菜を買った。","Ichiba de yasai o katta.","Membeli sayuran di pasar."),
    ("場","ば/じょう","tempat/lokasi","駐車場はどこですか。","Chuushajou wa doko desuka.","Di mana tempat parkirnya?"),
    ("所","ところ/しょ","tempat","好きな場所はどこですか。","Sukina basho wa doko desuka.","Di mana tempat favoritmu?"),
    ("部","ぶ","bagian/departemen","営業部に所属しています。","Eigyoubu ni shozoku shite imasu.","Saya tergabung di bagian penjualan."),
    ("室","しつ","ruangan/kamar","会議室を予約した。","Kaigishitsu o yoyaku shita.","Memesan ruang rapat."),
    ("館","かん","gedung/bangunan","図書館で本を借りた。","Toshokan de hon o karita.","Meminjam buku di perpustakaan."),
    ("院","いん","institusi/gedung","病院で検査を受けた。","Byouin de kensa o uketa.","Menjalani pemeriksaan di rumah sakit."),
    ("校","こう","sekolah","母校を訪問した。","Boukou o houmon shita.","Mengunjungi sekolah almamater."),
    ("学","まなぶ/がく","belajar","学校で学びます。","Gakkou de manabimasu.","Belajar di sekolah."),
    ("科","か","jurusan/ilmu","理科が好きです。","Rika ga suki desu.","Saya suka ilmu alam."),
    ("試","こころ/し","mencoba/ujian","試験を受けた。","Shiken o uketa.","Mengikuti ujian."),
    ("験","けん","ujian/pengalaman","試験の結果が出た。","Shiken no kekka ga deta.","Hasil ujian sudah keluar."),
    ("研","けん","meneliti","研究室で実験をする。","Kenkyuushitsu de jikken o suru.","Melakukan eksperimen di lab."),
    ("究","きゅう","meneliti/mencari tahu","研究の結果を発表した。","Kenkyuu no kekka o happyou shita.","Mempresentasikan hasil penelitian."),
    ("発","はつ/ほつ","berangkat/mengeluarkan","新幹線が発車しました。","Shinkansen ga hassha shimashita.","Shinkansen sudah berangkat."),
    ("表","おもて/ひょう","permukaan/tabel/mengumumkan","結果を発表した。","Kekka o happyou shita.","Mengumumkan hasilnya."),
    ("現","あらわ/げん","muncul/sekarang","現在どこにいますか。","Genzai doko ni imasu ka.","Sekarang kamu di mana?"),
    ("代","か/だい","menggantikan/generasi","世代交代が起きている。","Sedai koutai ga okite iru.","Pergantian generasi sedang terjadi."),
    ("世","よ/せ","dunia/generasi","世界中を旅したい。","Sekaijuu o tabi shitai.","Ingin berkeliling dunia."),
    ("界","かい","dunia/batas","業界のことを調べた。","Gyoukai no koto o shirabeta.","Meneliti tentang industri."),
    ("国","くに/こく","negara","日本は島国です。","Nihon wa shimaguni desu.","Jepang adalah negara kepulauan."),
    ("外","そと/がい","luar","外は寒いです。","Soto wa samui desu.","Di luar dingin."),
    ("内","うち/ない","dalam/domestik","国内旅行が好きです。","Kokunai ryokou ga suki desu.","Suka perjalanan domestik."),
    ("地","ち/じ","tanah/tempat","地図で確認する。","Chizu de kakunin suru.","Mengecek di peta."),
    ("図","はか/ず","gambar/rencana","地図を見ながら歩く。","Chizu o minagara aruku.","Berjalan sambil melihat peta."),
    ("道","みち/どう","jalan","この道はどこに続いていますか。","Kono michi wa doko ni tsuzuite imasu ka.","Jalan ini menuju ke mana?"),
    ("橋","はし/きょう","jembatan","川に橋を架けた。","Kawa ni hashi o kaketa.","Membangun jembatan di sungai."),
    ("駅","えき","stasiun","駅まで歩いて10分です。","Eki made aruite juppun desu.","10 menit jalan kaki ke stasiun."),
    ("港","みなと/こう","pelabuhan","神戸港は有名です。","Koube-kou wa yuumei desu.","Pelabuhan Kobe terkenal."),
    ("空","そら/くう","langit/kosong","空が青い。","Sora ga aoi.","Langit biru."),
    ("海","うみ/かい","laut","海で泳いだ。","Umi de oyoida.","Berenang di laut."),
    ("山","やま/さん","gunung","山に登るのが好きです。","Yama ni noboru no ga suki desu.","Suka mendaki gunung."),
    ("川","かわ/せん","sungai","川が静かに流れている。","Kawa ga shizuka ni nagarete iru.","Sungai mengalir dengan tenang."),
    ("池","いけ/ち","kolam","公園の池に魚がいる。","Kouen no ike ni sakana ga iru.","Ada ikan di kolam taman."),
    ("森","もり/しん","hutan","森の中を歩いた。","Mori no naka o aruita.","Berjalan di dalam hutan."),
    ("林","はやし/りん","hutan kecil/rimba","林の中で鳥を見た。","Hayashi no naka de tori o mita.","Melihat burung di dalam rimba."),
    ("花","はな/か","bunga","花を買います。","Hana o kaimasu.","Membeli bunga."),
    ("草","くさ/そう","rumput","草原を歩いた。","Sougen o aruita.","Berjalan di padang rumput."),
    ("木","き/もく","pohon","公園に木がたくさんある。","Kouen ni ki ga takusan aru.","Banyak pohon di taman."),
    ("石","いし/せき","batu","川で石を拾った。","Kawa de ishi o hirotta.","Memungut batu di sungai."),
    ("雨","あめ/う","hujan","今日は雨です。","Kyou wa ame desu.","Hari ini hujan."),
    ("雪","ゆき/せつ","salju","雪が降っています。","Yuki ga futte imasu.","Salju sedang turun."),
    ("風","かぜ/ふう","angin","強い風が吹いている。","Tsuyoi kaze ga fuite iru.","Angin kencang berhembus."),
    ("雲","くも/うん","awan","空に雲が多い。","Sora ni kumo ga ooi.","Banyak awan di langit."),
    ("晴","は/せい","cerah","明日は晴れるでしょう。","Ashita wa hareru deshou.","Besok mungkin akan cerah."),
    ("温","あたた/おん","hangat/suhu","温かいスープを飲んだ。","Atatakai suupu o nonda.","Minum sup yang hangat."),
    ("熱","あつ/ねつ","panas/demam","熱が出た。","Netsu ga deta.","Demam muncul."),
    ("冷","つめ/れい","dingin/pendingin","冷たい水を飲んだ。","Tsumetai mizu o nonda.","Minum air dingin."),
    ("色","いろ/しょく","warna","好きな色は何ですか。","Sukina iro wa nan desuka.","Warna favoritmu apa?"),
    ("形","かたち/けい","bentuk","丸い形が好きです。","Marui katachi ga suki desu.","Suka bentuk bulat."),
    ("様","よう/さま","cara/gelar hormat","お客様をお待ちしています。","Okyakusama o omachi shite imasu.","Menunggu tamu."),
    ("方","かた/ほう","cara/arah","使い方を教えてください。","Tsukaikata o oshiete kudasai.","Tolong ajarkan cara pakainya."),
    ("法","ほう/のり","hukum/cara","方法を工夫する。","Houhou o kuufuu suru.","Memikirkan cara yang lebih baik."),
    ("理","り","alasan/logika","理由を教えてください。","Riyuu o oshiete kudasai.","Tolong beritahu alasannya."),
    ("由","ゆ/ゆう","alasan/kebebasan","自由に選んでください。","Jiyuu ni erande kudasai.","Tolong pilih dengan bebas."),
    ("意","い","maksud/pikiran","意味が分かりません。","Imi ga wakarimasen.","Tidak mengerti artinya."),
    ("味","あじ/み","rasa/minat","この料理は味がいい。","Kono ryouri wa aji ga ii.","Masakan ini rasanya enak."),
    ("気","き/け","perasaan/udara","元気ですか。","Genki desuka.","Apa kabar?"),
    ("神","かみ/しん","dewa/Tuhan","神社にお参りした。","Jinja ni omairi shita.","Berziarah ke kuil Shinto."),
    ("仏","ほとけ/ぶつ","Buddha","お寺でお仏像を見た。","Otera de obusou o mita.","Melihat patung Buddha di kuil."),
    ("命","いのち/めい","nyawa/perintah","命を大切にする。","Inochi o taisetsu ni suru.","Menghargai kehidupan."),
    ("血","ち/けつ","darah","血液検査をした。","Ketsueki kensa o shita.","Melakukan tes darah."),
    ("肉","にく","daging","牛肉が好きです。","Gyuuniku ga suki desu.","Suka daging sapi."),
    ("骨","ほね/こつ","tulang","骨が折れた。","Hone ga oreta.","Tulang patah."),
    ("皮","かわ/ひ","kulit","果物の皮をむく。","Kudamono no kawa o muku.","Mengupas kulit buah."),
    ("毛","け/もう","rambut/bulu","犬の毛が抜けた。","Inu no ke ga nuketa.","Bulu anjing rontok."),
    ("歯","は/し","gigi","歯を磨いてください。","Ha o migaite kudasai.","Tolong sikat giginya."),
    ("鼻","はな/び","hidung","鼻が痛い。","Hana ga itai.","Hidung sakit."),
    ("目","め/もく","mata","目が疲れた。","Me ga tsukareta.","Mata lelah."),
    ("耳","みみ/じ","telinga","耳が痛い。","Mimi ga itai.","Telinga sakit."),
    ("口","くち/こう","mulut","口を大きく開けてください。","Kuchi o ookiku akete kudasai.","Tolong buka mulut lebar-lebar."),
    ("手","て/しゅ","tangan","手を洗います。","Te o araimasu.","Mencuci tangan."),
    ("足","あし/そく","kaki","足が疲れた。","Ashi ga tsukareta.","Kaki lelah."),
    ("背","せ/はい","punggung/tinggi badan","背が高いですね。","Se ga takai desu ne.","Tinggi badannya tinggi ya."),
    ("腹","はら/ふく","perut","お腹が空いた。","Onaka ga suita.","Lapar."),
    ("胸","むね/きょう","dada","胸が痛い。","Mune ga itai.","Dada sakit."),
    ("肩","かた/けん","bahu","肩が凝っている。","Kata ga kotte iru.","Bahu pegal."),
    ("腕","うで/わん","lengan","腕を骨折した。","Ude o kossetsu shita.","Lengan patah tulang."),
    ("指","ゆび/し","jari","指を切ってしまった。","Yubi o kitte shimatta.","Jari terpotong."),
    ("服","ふく","pakaian","新しい服を買った。","Atarashii fuku o katta.","Membeli pakaian baru."),
    ("靴","くつ","sepatu","靴を脱いでください。","Kutsu o nuide kudasai.","Tolong lepas sepatu."),
    ("帽","ぼう","topi","帽子をかぶってください。","Boushi o kabutte kudasai.","Tolong pakai topi."),
    ("袋","ふくろ/たい","kantong/tas","袋に入れてください。","Fukuro ni irete kudasai.","Tolong masukkan ke kantong."),
    ("箱","はこ","kotak","箱の中に入れた。","Hako no naka ni ireta.","Memasukkan ke dalam kotak."),
    ("机","つくえ/き","meja (belajar)","机の上を片付けた。","Tsukue no ue o katazuketa.","Membereskan atas meja."),
    ("椅","い","kursi","椅子に座ってください。","Isu ni suwatte kudasai.","Tolong duduk di kursi."),
    ("窓","まど/そう","jendela","窓を開けてください。","Mado o akete kudasai.","Tolong buka jendelanya."),
    ("壁","かべ/へき","dinding","壁に絵を飾った。","Kabe ni e o kazatta.","Menghias dinding dengan gambar."),
    ("床","ゆか/しょう","lantai","床を掃除した。","Yuka o souji shita.","Membersihkan lantai."),
    ("天","てん","langit/surga","天気がいいですね。","Tenki ga ii desu ne.","Cuacanya bagus ya."),
    ("屋","や/おく","atap/ruangan","屋根が赤い家です。","Yane ga akai ie desu.","Rumah dengan atap merah."),
    ("階","かい","lantai (bertingkat)","3階に住んでいます。","Sankkai ni sunde imasu.","Tinggal di lantai 3."),
    ("段","だん","tangga/tingkatan","階段を上がった。","Kaidan o agatta.","Naik tangga."),
    ("電","でん","listrik","電気をつけてください。","Denki o tsukete kudasai.","Tolong nyalakan lampu."),
    ("話","はな/わ","berbicara","電話で話した。","Denwa de hanashita.","Berbicara lewat telepon."),
    ("紙","かみ/し","kertas","紙に書いてください。","Kami ni kaite kudasai.","Tolong tulis di kertas."),
    ("本","ほん/もと","buku/asal","本を読むのが好きです。","Hon o yomu no ga suki desu.","Suka membaca buku."),
    ("字","じ","huruf/karakter","この字は何と読みますか。","Kono ji wa nanto yomimasu ka.","Huruf ini dibaca apa?"),
    ("文","ふみ/もん","tulisan/kalimat","文章を書く練習をする。","Bunshou o kaku renshuu o suru.","Berlatih menulis kalimat."),
    ("記","き","mencatat/ingatan","日記を毎日書いています。","Nikki o mainichi kaite imasu.","Menulis buku harian setiap hari."),
    ("写","うつ/しゃ","menyalin/foto","写真を撮ってください。","Shashin o totte kudasai.","Tolong ambil foto."),
    ("画","かく/が","gambar/film","映画を見に行った。","Eiga o mi ni itta.","Pergi menonton film."),
    ("音","おと/おん","suara/bunyi","音楽を聴いています。","Ongaku o kiite imasu.","Sedang mendengarkan musik."),
    ("楽","たの/らく","menyenangkan/mudah","音楽を聴くのが楽しい。","Ongaku o kiku no ga tanoshii.","Mendengarkan musik menyenangkan."),
    ("歌","うた/か","lagu/bernyanyi","好きな歌を歌った。","Sukina uta o utatta.","Menyanyikan lagu favorit."),
    ("運","はこ/うん","nasib/mengangkut","運動は健康にいい。","Undou wa kenkou ni ii.","Olahraga baik untuk kesehatan."),
    ("動","うご/どう","bergerak","体を動かすことが大切だ。","Karada o ugokasu koto ga taisetsu da.","Menggerakkan tubuh itu penting."),
    ("球","たま/きゅう","bola","野球が好きです。","Yakyuu ga suki desu.","Suka baseball."),
    ("試","し","pertandingan/mencoba","試合に出た。","Shiai ni deta.","Keluar dalam pertandingan."),
    ("賞","しょう","hadiah/penghargaan","賞をもらった。","Shou o moratta.","Mendapat penghargaan."),
    ("記","き","mencatat/rekam","記録を更新した。","Kiroku o koushin shita.","Memperbarui rekor."),
    ("親","しん","orang tua","両親に感謝する。","Ryoushin ni kansha suru.","Berterima kasih kepada orang tua."),
    ("家","いえ/か","rumah/keluarga","家族と一緒に住んでいる。","Kazoku to issho ni sunde iru.","Tinggal bersama keluarga."),
    ("族","ぞく","kelompok/suku","家族旅行を計画した。","Kazoku ryokou o keikaku shita.","Merencanakan liburan keluarga."),
    ("者","もの/しゃ","orang/pelaku","医者に行った。","Isha ni itta.","Pergi ke dokter."),
    ("員","いん","anggota/staf","会社の社員が増えた。","Kaisha no shain ga fueta.","Jumlah karyawan bertambah."),
    ("長","ちょう","kepala/pimpinan","部長に報告した。","Buchou ni houkoku shita.","Melapor kepada kepala bagian."),
    ("係","かかり/けい","petugas/hubungan","受付係に聞いた。","Uketsuke-gakari ni kiita.","Bertanya kepada petugas resepsionis."),
    ("社","しゃ","perusahaan/kuil","会社に就職した。","Kaisha ni shuushoku shita.","Mendapat pekerjaan di perusahaan."),
    ("会","かい","pertemuan/perkumpulan","会議に出席した。","Kaigi ni shusseki shita.","Menghadiri rapat."),
    ("議","ぎ","rapat/musyawarah","会議で決定した。","Kaigi de kettei shita.","Diputuskan dalam rapat."),
    ("政","せい","pemerintahan/politik","政治に興味がある。","Seiji ni kyoumi ga aru.","Tertarik dengan politik."),
    ("府","ふ","pemerintah daerah","大阪府に住んでいます。","Oosaka-fu ni sunde imasu.","Tinggal di Prefektur Osaka."),
    ("県","けん","prefektur","神奈川県に住んでいます。","Kanagawa-ken ni sunde imasu.","Tinggal di Prefektur Kanagawa."),
    ("市","し","kota","東京市内を観光した。","Toukyou shinai o kankou shita.","Wisata di dalam kota Tokyo."),
    ("区","く","distrik/zona","この区に住んでいます。","Kono ku ni sunde imasu.","Tinggal di distrik ini."),
    ("町","まち/ちょう","kota kecil/desa","静かな町に住みたい。","Shizuka na machi ni sumitai.","Ingin tinggal di kota yang tenang."),
    ("村","むら/そん","desa","田舎の村で育った。","Inaka no mura de sodatta.","Tumbuh besar di desa pedesaan."),
    ("番","ばん","penjagaan/nomor","今日は私の番です。","Kyou wa watashi no ban desu.","Hari ini giliran saya."),
    ("局","きょく","kantor/bagian","郵便局で切手を買った。","Yuubinkyoku de kitte o katta.","Membeli perangko di kantor pos."),
    ("物","もの/ぶつ","benda/hal","買い物に行きます。","Kaimono ni ikimasu.","Pergi belanja."),
    ("事","こと/じ","hal/pekerjaan","仕事が忙しい。","Shigoto ga isogashii.","Pekerjaan sibuk."),
    ("知","し/ち","pengetahuan","知識を増やしたい。","Chishiki o fuyashitai.","Ingin menambah pengetahuan."),
    ("識","しき","pengetahuan/kesadaran","常識が大切です。","Joushiki ga taisetsu desu.","Pengetahuan umum itu penting."),
    ("経","へ/けい","melewati/ekonomi","経験が大切です。","Keiken ga taisetsu desu.","Pengalaman itu penting."),
    ("済","す/さい","selesai/ekonomi","経済が発展している。","Keizai ga hatten shite iru.","Ekonomi sedang berkembang."),
    ("活","かつ","aktivitas/hidup","生活費が高い。","Seikatsuhi ga takai.","Biaya hidup mahal."),
    ("用","もち/よう","menggunakan/keperluan","この道具は何に用いますか。","Kono dougu wa nani ni mochiimasu ka.","Alat ini digunakan untuk apa?"),
    ("必","かなら/ひつ","pasti/perlu","必要な書類を用意した。","Hitsuyou na shorui o youi shita.","Menyiapkan dokumen yang diperlukan."),
    ("要","い/よう","perlu/penting","練習が必要です。","Renshuu ga hitsuyou desu.","Latihan diperlukan."),
    ("全","まった/ぜん","semua/lengkap","全部食べた。","Zenbu tabeta.","Makan semua."),
    ("部","すべ/ぶ","semua/bagian","全部終わりました。","Zenbu owarimashita.","Semua sudah selesai."),
    ("各","かく","masing-masing","各自で準備してください。","Kakuji de junbi shite kudasai.","Tolong bersiap masing-masing."),
    ("両","りょう","keduanya/dua","両親が来た。","Ryoushin ga kita.","Kedua orang tua datang."),
    ("互","たが/ご","saling","お互いに協力しよう。","Otagai ni kyouryoku shiyou.","Mari saling bekerja sama."),
    ("共","とも/きょう","bersama","一緒に行こう。","Issho ni ikou.","Mari pergi bersama."),
    ("別","べつ","lain/berbeda","別の方法を試した。","Betsu no houhou o tameshita.","Mencoba cara yang lain."),
    ("特","とく","khusus/istimewa","特別な日です。","Tokubetsu na hi desu.","Hari istimewa."),
    ("普","ふ","biasa/umum","普通の生活をしている。","Futsuu no seikatsu o shite iru.","Menjalani kehidupan biasa."),
    ("通","とお/つう","melewati/biasa","この道を通ってください。","Kono michi o tootte kudasai.","Tolong lewat jalan ini."),
    ("過","す/か","melewati/terlalu","時間が過ぎた。","Jikan ga sugita.","Waktu sudah berlalu."),
    ("去","さ/きょ","pergi/lalu","去年日本に行きました。","Kyonen Nihon ni ikimashita.","Tahun lalu pergi ke Jepang."),
    ("来","く/らい","datang/masa depan","来年また来ます。","Rainen mata kimasu.","Tahun depan datang lagi."),
    ("将","しょう","akan datang/jenderal","将来の夢は医者です。","Shourai no yume wa isha desu.","Impian masa depan adalah dokter."),
    ("未","み","belum/masa depan","未来が楽しみです。","Mirai ga tanoshimi desu.","Menantikan masa depan."),
    ("済","さい","sudah/selesai","準備が済みました。","Junbi ga sumimashita.","Persiapan sudah selesai."),
    ("完","かん","selesai/sempurna","仕事が完成した。","Shigoto ga kansei shita.","Pekerjaan sudah selesai."),
    ("成","な/せい","menjadi/berhasil","目標を達成した。","Mokuhyou o tassei shita.","Mencapai tujuan."),
    ("達","たち/たつ","mencapai/jamak orang","友達が来た。","Tomodachi ga kita.","Teman datang."),
    ("進","すす/しん","maju","計画が進んでいる。","Keikaku ga susunde iru.","Rencana sedang maju."),
    ("退","しりぞ/たい","mundur/pensiun","会社を退職した。","Kaisha o taishoku shita.","Pensiun dari perusahaan."),
    ("向","む/こう","menghadap/menuju","駅に向かっています。","Eki ni mukatte imasu.","Sedang menuju stasiun."),
    ("反","そ/はん","melawan/membalik","反対意見を述べた。","Hantai iken o nobeta.","Menyatakan pendapat yang menentang."),
    ("対","たい","melawan/pasangan","試合で対戦する。","Shiai de taisen suru.","Bertanding dalam pertandingan."),
    ("相","あい/そう","saling/wajah","相談に乗ってください。","Soudan ni notte kudasai.","Tolong dengarkan konsultasi saya."),
    ("互","ご","saling","互いに助け合う。","Tagai ni tasuke au.","Saling membantu satu sama lain."),
    ("協","きょう","bekerja sama","チームで協力した。","Chiimu de kyouryoku shita.","Bekerja sama dalam tim."),
    ("力","ちから/りょく","kekuatan/tenaga","皆で力を合わせた。","Minna de chikara o awaseta.","Semua menyatukan kekuatan."),
    ("支","さ/し","mendukung/cabang","友人が私を支えてくれた。","Yuujin ga watashi o sasaete kureta.","Teman mendukung saya."),
    ("援","えん","membantu/mendukung","支援をありがとうございます。","Shien o arigatou gozaimasu.","Terima kasih atas dukungannya."),
    ("救","すく/きゅう","menyelamatkan","命を救った。","Inochi o sukutta.","Menyelamatkan nyawa."),
    ("守","まも/しゅ","menjaga/melindungi","家族を守る。","Kazoku o mamoru.","Melindungi keluarga."),
    ("安","やす/あん","aman/murah","安全な道を歩く。","Anzen na michi o aruku.","Berjalan di jalan yang aman."),
    ("全","ぜん","lengkap/aman","安全第一です。","Anzen daiichi desu.","Keselamatan adalah prioritas utama."),
    ("危","あぶ/き","berbahaya","危険な場所に行かない。","Kiken na basho ni ikanai.","Tidak pergi ke tempat berbahaya."),
    ("険","けん","bahaya/curam","危険を避けてください。","Kiken o sakete kudasai.","Tolong hindari bahaya."),
    ("病","や/びょう","sakit/penyakit","病気で学校を休んだ。","Byouki de gakkou o yasunda.","Tidak masuk sekolah karena sakit."),
    ("薬","くすり/やく","obat","薬を飲んでください。","Kusuri o nonde kudasai.","Tolong minum obatnya."),
    ("医","い","dokter/mengobati","医者に診てもらった。","Isha ni mite moratta.","Diperiksa dokter."),
    ("治","なお/じ","menyembuhkan","病気が治った。","Byouki ga naotta.","Penyakitnya sembuh."),
    ("健","けん","sehat","健康が大切です。","Kenkou ga taisetsu desu.","Kesehatan itu penting."),
    ("康","こう","sehat/sejahtera","健康な体を作る。","Kenkou na karada o tsukuru.","Membangun tubuh yang sehat."),
    ("洗","あら/せん","mencuci","顔を洗った。","Kao o aratta.","Mencuci muka."),
    ("清","きよ/せい","bersih/murni","清潔にしてください。","Seiketsu ni shite kudasai.","Tolong jaga kebersihan."),
    ("汚","よご/お","kotor","部屋が汚い。","Heya ga kitanai.","Kamarnya kotor."),
    ("整","ととの/せい","merapikan/mengatur","部屋を整理した。","Heya o seiri shita.","Merapikan kamar."),
    ("掃","は/そう","menyapu/membersihkan","部屋を掃除した。","Heya o souji shita.","Membersihkan kamar."),
    ("料","りょう","masakan/biaya","料理を作った。","Ryouri o tsukutta.","Membuat masakan."),
    ("食","た/しょく","makanan/makan","食事をしてください。","Shokuji o shite kudasai.","Tolong makan."),
    ("飲","の/いん","minum","水を飲みます。","Mizu o nomimasu.","Minum air."),
    ("味","あじ/み","rasa","この料理は美味しい。","Kono ryouri wa oishii.","Masakan ini enak."),
    ("辛","から/しん","pedas/berat","辛い料理が好きです。","Karai ryouri ga suki desu.","Suka masakan pedas."),
    ("甘","あま/かん","manis","甘いものが好きです。","Amai mono ga suki desu.","Suka yang manis."),
    ("苦","にが/く","pahit/sulit","苦い薬を飲んだ。","Nigai kusuri o nonda.","Minum obat yang pahit."),
    ("酸","す/さん","asam","酸っぱいレモンです。","Suppai remon desu.","Lemon yang asam."),
    ("塩","しお/えん","garam","塩を少し入れてください。","Shio o sukoshi irete kudasai.","Tolong masukkan sedikit garam."),
    ("砂","さ/しゃ","pasir","砂糖を入れた。","Satou o ireta.","Memasukkan gula."),
    ("油","あぶら/ゆ","minyak","油で炒めた。","Abura de itameta.","Menumis dengan minyak."),
]

# ============================================================
# 700 KOSAKATA N4
# ============================================================
VOCAB = [
    ("あいかわらず","seperti biasa","相変わらず元気ですか。","Aikawarazu genki desuka.","Apakah kamu masih sehat seperti biasa?"),
    ("あいだに","selagi/sementara","雨が降っているあいだに準備した。","Ame ga futte iru aida ni junbi shita.","Bersiap selagi hujan turun."),
    ("あげる","memberikan","友達にプレゼントをあげた。","Tomodachi ni purezento o ageta.","Memberi hadiah kepada teman."),
    ("あきらめる","menyerah","夢をあきらめないで。","Yume o akiramenaide.","Jangan menyerah pada impianmu."),
    ("あたりまえ","sudah sewajarnya","努力するのはあたりまえだ。","Doryoku suru no wa atarimae da.","Berusaha keras itu wajar."),
    ("あとで","nanti/setelah itu","あとで電話します。","Ato de denwa shimasu.","Nanti saya telepon."),
    ("あつまる","berkumpul","みんなが公園に集まった。","Minna ga kouen ni atsumatta.","Semua berkumpul di taman."),
    ("あやまる","meminta maaf","失敗したのであやまった。","Shippai shita node ayamatta.","Meminta maaf karena gagal."),
    ("あらわす","mengungkapkan","気持ちを言葉で表す。","Kimochi o kotoba de arawasu.","Mengungkapkan perasaan dengan kata-kata."),
    ("いきなり","tiba-tiba/mendadak","いきなり雨が降ってきた。","Ikinari ame ga futte kita.","Tiba-tiba hujan turun."),
    ("いくら〜ても","seberapa pun","いくら練習してもうまくならない。","Ikura renshuu shite mo umaku naranai.","Meskipun berlatih sebanyak apapun tidak mahir."),
    ("いつのまにか","tanpa terasa","いつのまにか夜になった。","Itsu no ma ni ka yoru ni natta.","Tanpa terasa sudah malam."),
    ("いまさら","sekarang baru/terlambat","今さら言っても遅い。","Imasara itte mo osoi.","Terlambat sudah untuk dikatakan sekarang."),
    ("うかがう","mengunjungi (sopan)","明日うかがってもよいですか。","Ashita ukagatte mo yoi desuka.","Bolehkah saya datang besok?"),
    ("うける","menerima/mengikuti ujian","試験を受けます。","Shiken o ukemasu.","Mengikuti ujian."),
    ("うまい","enak/mahir","この料理はうまい。","Kono ryouri wa umai.","Masakan ini enak."),
    ("うまくいく","berjalan dengan baik","計画がうまくいった。","Keikaku ga umaku itta.","Rencananya berjalan dengan baik."),
    ("えんりょなく","tanpa sungkan","遠慮なく食べてください。","Enryo naku tabete kudasai.","Silakan makan tanpa sungkan."),
    ("おかえり","selamat datang (pulang)","おかえりなさい。","Okaerinasai.","Selamat datang kembali."),
    ("おかげさまで","berkat Anda","おかげさまで元気です。","Okagesama de genki desu.","Berkat Anda saya sehat."),
    ("おきにいり","favorit/kesukaan","これが私のお気に入りです。","Kore ga watashi no okiniiri desu.","Ini favorit saya."),
    ("おじゃまします","permisi masuk ke rumah","おじゃまします。","Ojama shimasu.","Permisi saya masuk ya."),
    ("おせわになる","mendapat bantuan","大変お世話になりました。","Taihen osewa ni narimashita.","Terima kasih banyak atas bantuan Anda."),
    ("おたがいさま","sama-sama","お互いさまです。","Otagai sama desu.","Kita sama-sama."),
    ("おつかれさま","terima kasih sudah bekerja keras","お疲れ様でした。","Otsukare sama deshita.","Terima kasih sudah bekerja keras."),
    ("おもいきり","sekuat tenaga/sepuasnya","思い切り楽しんだ。","Omoikiri tanoshinda.","Bersenang-senang sepuasnya."),
    ("おもいやり","empati/perhatian","思いやりのある人が好きだ。","Omoiyari no aru hito ga suki da.","Suka orang yang penuh empati."),
    ("おわりに","di akhir/sebagai penutup","おわりに感謝を述べます。","Owari ni kansha o nobemasu.","Di akhir saya menyampaikan rasa terima kasih."),
    ("かいぎ","rapat","午後から会議があります。","Gogo kara kaigi ga arimasu.","Ada rapat dari siang."),
    ("かえって","justru/malah","薬を飲んだらかえって悪くなった。","Kusuri o nondara kaette waruku natta.","Setelah minum obat justru semakin buruk."),
    ("かかわる","berhubungan/terlibat","この問題に関わっています。","Kono mondai ni kakawatte imasu.","Terlibat dalam masalah ini."),
    ("かかる","membutuhkan (waktu/biaya)","時間がかかります。","Jikan ga kakarimasu.","Membutuhkan waktu."),
    ("かぎる","membatasi","参加者を10人に限る。","Sankasha o juunin ni kagiru.","Membatasi peserta hingga 10 orang."),
    ("かくにん","konfirmasi","予約を確認してください。","Yoyaku o kakunin shite kudasai.","Tolong konfirmasi reservasinya."),
    ("かさなる","bertumpuk","問題が重なってしまった。","Mondai ga kasanatte shimatta.","Masalah bertumpuk-tumpuk."),
    ("かたづける","membereskan","部屋を片付けた。","Heya o katazuketa.","Membereskan kamar."),
    ("かならず","pasti/tentu","必ず時間を守ってください。","Kanarazu jikan o mamotte kudasai.","Tolong pasti tepat waktu."),
    ("かんがえかた","cara berpikir","考え方を変えてみよう。","Kangaekata o kaete miyou.","Mari mencoba mengubah cara berpikir."),
    ("かんきょう","lingkungan","環境を守ることが大切だ。","Kankyou o mamoru koto ga taisetsu da.","Menjaga lingkungan itu penting."),
    ("かんけい","hubungan/kaitan","この問題と関係がある。","Kono mondai to kankei ga aru.","Ada hubungannya dengan masalah ini."),
    ("かんしゃ","rasa syukur","感謝の気持ちを忘れない。","Kansha no kimochi o wasurenai.","Tidak melupakan rasa syukur."),
    ("かんじる","merasakan","春の暖かさを感じる。","Haru no atatakasa o kanjiru.","Merasakan hangatnya musim semi."),
    ("かんたん","mudah/sederhana","この問題は簡単です。","Kono mondai wa kantan desu.","Soal ini mudah."),
    ("かんりする","mengelola","プロジェクトを管理する。","Purojekuto o kanri suru.","Mengelola proyek."),
    ("きかい","kesempatan/mesin","このチャンスを活かしたい。","Kono chansu o ikashitai.","Ingin memanfaatkan kesempatan ini."),
    ("きけん","bahaya","危険な場所に近づかない。","Kiken na basho ni chikazukanai.","Tidak mendekati tempat berbahaya."),
    ("きびしい","keras/ketat","先生は厳しいが優しい。","Sensei wa kibishii ga yasashii.","Gurunya ketat tapi baik hati."),
    ("きまる","diputuskan","日程が決まりました。","Nittei ga kimarimashita.","Jadwalnya sudah ditetapkan."),
    ("きゅうに","tiba-tiba","急に雨が降り始めた。","Kyuu ni ame ga furihajimeta.","Tiba-tiba hujan mulai turun."),
    ("きをつける","berhati-hati","車に気をつけてください。","Kuruma ni ki o tsukete kudasai.","Tolong berhati-hati dengan mobil."),
    ("くらべる","membandingkan","二つを比べてみた。","Futatsu o kurabete mita.","Mencoba membandingkan keduanya."),
    ("けいかく","rencana","旅行の計画を立てた。","Ryokou no keikaku o tateta.","Membuat rencana perjalanan."),
    ("けいけん","pengalaman","海外での経験が役立つ。","Kaigai de no keiken ga yakudatsu.","Pengalaman di luar negeri berguna."),
    ("けいざい","ekonomi","経済が発展している。","Keizai ga hatten shite iru.","Ekonomi sedang berkembang."),
    ("けっか","hasil/akibat","努力の結果が出た。","Doryoku no kekka ga deta.","Hasil dari kerja keras sudah keluar."),
    ("けっして","sama sekali tidak","決して諦めません。","Kesshite akiramemasen.","Sama sekali tidak akan menyerah."),
    ("けんか","pertengkaran","友達とけんかしてしまった。","Tomodachi to kenka shite shimatta.","Bertengkar dengan teman."),
    ("こうこう","SMA/SMU","高校に通っています。","Koukou ni kayotte imasu.","Sedang bersekolah di SMA."),
    ("こうどう","tindakan/perilaku","積極的に行動する。","Sekkyokuteki ni koudou suru.","Bertindak secara aktif."),
    ("こうはい","junior/adik kelas","後輩の面倒を見る。","Kouhai no mendou o miru.","Mengurus adik kelas."),
    ("こえ","suara","大きな声で話してください。","Ookina koe de hanashite kudasai.","Tolong bicara dengan suara keras."),
    ("こころがける","berusaha/memperhatikan","礼儀正しくすることを心がける。","Reigi tadashiku suru koto o kokorogakeru.","Berusaha untuk selalu bersikap sopan."),
    ("こころよい","menyenangkan/mau","快い返事をもらった。","Kokoroyoi henji o moratta.","Mendapat jawaban yang menyenangkan."),
    ("ことわる","menolak","誘いを断った。","Sasoi o kotowatta.","Menolak ajakan."),
    ("このごろ","belakangan ini","このごろ忙しいです。","Konogoro isogashii desu.","Belakangan ini sibuk."),
    ("こまかい","detail/kecil","細かいことまで確認する。","Komakai koto made kakunin suru.","Mengecek sampai detail kecil."),
    ("こむ","ramai/penuh sesak","電車がとても込んでいる。","Densha ga totemo konde iru.","Kereta sangat penuh sesak."),
    ("こんご","mulai sekarang/ke depan","今後ともよろしくお願いします。","Kongo tomo yoroshiku onegai shimasu.","Mohon kerja samanya ke depan."),
    ("さいきん","baru-baru ini","最近忙しくなった。","Saikin isogashiku natta.","Akhir-akhir ini semakin sibuk."),
    ("さいご","terakhir/akhir","最後まで頑張ってください。","Saigo made ganbatte kudasai.","Tolong semangat sampai akhir."),
    ("さいしょ","pertama/awal","最初から始めましょう。","Saisho kara hajimemashou.","Mari mulai dari awal."),
    ("さいてい","terendah/minimal","最低でも1時間は練習する。","Saiteide mo ichijikan wa renshuu suru.","Minimal berlatih 1 jam."),
    ("さいのう","bakat/kemampuan","彼女は才能がある。","Kanojo wa sainou ga aru.","Dia punya bakat."),
    ("さらに","lebih lagi/selain itu","さらに詳しく説明します。","Sara ni kuwashiku setsumei shimasu.","Akan menjelaskan lebih detail lagi."),
    ("しかた","cara/metode","やり方を教えてください。","Yarikata o oshiete kudasai.","Tolong ajarkan caranya."),
    ("しかたがない","tidak bisa diapa-apakan","遅刻したのはしかたがない。","Chikoku shita no wa shikata ga nai.","Terlambat itu tidak bisa diapa-apakan."),
    ("しかし","namun/tetapi","難しい。しかし諦めない。","Muzukashii. Shikashi akiramenai.","Sulit. Namun tidak menyerah."),
    ("じかん","waktu","時間を大切にする。","Jikan o taisetsu ni suru.","Menghargai waktu."),
    ("じっさい","kenyataannya","実際に試してみた。","Jissai ni tameshite mita.","Mencoba dalam kenyataan."),
    ("じつは","sebenarnya","実は昨日行けなかった。","Jitsu wa kinou ikenakatta.","Sebenarnya kemarin tidak bisa pergi."),
    ("しばらく","sebentar/sementara waktu","しばらく待ってください。","Shibaraku matte kudasai.","Tolong tunggu sebentar."),
    ("じゃあ","kalau begitu","じゃあ、行きましょう。","Jaa, ikimashou.","Kalau begitu mari pergi."),
    ("じゅんび","persiapan","発表の準備をする。","Happyou no junbi o suru.","Mempersiapkan presentasi."),
    ("じょうほう","informasi","正確な情報が必要だ。","Seikaku na jouhou ga hitsuyou da.","Informasi yang akurat diperlukan."),
    ("じょうたい","kondisi/keadaan","体の状態を確認する。","Karada no joutai o kakunin suru.","Mengecek kondisi tubuh."),
    ("しらべる","menyelidiki","インターネットで調べた。","Intaanetto de shirabeta.","Mencari tahu di internet."),
    ("しんぱい","khawatir","心配しないでください。","Shinpai shinaide kudasai.","Jangan khawatir."),
    ("しんせつ","ramah/baik hati","親切な人が好きです。","Shinsetsu na hito ga suki desu.","Suka orang yang ramah."),
    ("しんちょう","hati-hati/tinggi badan","慎重に行動してください。","Shinchou ni koudou shite kudasai.","Tolong bertindak dengan hati-hati."),
    ("しんらい","kepercayaan","信頼できる人です。","Shinrai dekiru hito desu.","Orang yang dapat dipercaya."),
    ("すごい","luar biasa/hebat","すごい才能ですね。","Sugoi sainou desu ne.","Bakat yang luar biasa ya."),
    ("すすむ","maju/berkembang","勉強が順調に進んでいる。","Benkyou ga junchou ni susunde iru.","Belajar berjalan dengan lancar."),
    ("すっかり","sepenuhnya","すっかり忘れてしまった。","Sukkari wasurete shimatta.","Benar-benar sudah lupa."),
    ("せいかつ","kehidupan sehari-hari","健康的な生活を送る。","Kenkoukeki na seikatsu o okuru.","Menjalani kehidupan yang sehat."),
    ("せいちょう","pertumbuhan","子どもの成長が嬉しい。","Kodomo no seichou ga ureshii.","Senang melihat pertumbuhan anak."),
    ("せっかく","susah payah/khusus","せっかく来たのに会えなかった。","Sekkaku kita no ni aenakatta.","Sudah susah payah datang tapi tidak bisa bertemu."),
    ("ぜったいに","pasti/mutlak","絶対に諦めない。","Zettai ni akiramenai.","Pasti tidak akan menyerah."),
    ("せんぱい","senior/kakak angkatan","先輩に相談した。","Senpai ni soudan shita.","Berkonsultasi dengan senior."),
    ("そうだん","konsultasi","先生に相談した。","Sensei ni soudan shita.","Berkonsultasi dengan guru."),
    ("そだてる","membesarkan","植物を育てるのが好きだ。","Shokubutsu o sodateru no ga suki da.","Suka membesarkan tanaman."),
    ("それほど","sebegitu/separah itu","それほど難しくない。","Sorehodo muzukashiku nai.","Tidak sesulit itu."),
    ("そのうち","suatu saat nanti","そのうち慣れますよ。","Sono uchi naremasu yo.","Suatu saat nanti pasti terbiasa."),
    ("それに","selain itu/lagipula","安いし、それに美味しい。","Yasui shi, sore ni oishii.","Murah lagipula enak."),
    ("そろそろ","sudah waktunya","そろそろ出発しましょう。","Sorosoro shuppatsu shimashou.","Sudah waktunya berangkat."),
    ("たいいく","olahraga/pendidikan jasmani","体育の授業が好きです。","Taiiku no jugyou ga suki desu.","Suka pelajaran olahraga."),
    ("たいおう","merespons/menangani","問題に対応した。","Mondai ni taiou shita.","Menangani masalah."),
    ("たいせつ","penting/berharga","家族は大切な存在だ。","Kazoku wa taisetsu na sonzai da.","Keluarga adalah keberadaan yang berharga."),
    ("たいてい","biasanya/umumnya","たいてい7時に起きます。","Taitei shichiji ni okimasu.","Biasanya bangun jam 7."),
    ("たいへん","sangat/susah","仕事がたいへんです。","Shigoto ga taihen desu.","Pekerjaan sangat susah."),
    ("たしかに","memang benar","確かにそうですね。","Tashika ni sou desu ne.","Memang benar begitu ya."),
    ("たとえば","misalnya","たとえば、りんごや桃などです。","Tatoeba, ringo ya momo nado desu.","Misalnya apel atau persik."),
    ("たのしみ","kesenangan/menantikan","旅行が楽しみです。","Ryokou ga tanoshimi desu.","Menantikan perjalanan."),
    ("たのむ","meminta tolong/memesan","友達に手伝いを頼んだ。","Tomodachi ni tetsudai o tanonda.","Meminta tolong kepada teman."),
    ("たびたび","sering kali","たびたびお邪魔してすみません。","Tabitabi ojama shite sumimasen.","Maaf sering mengganggu."),
    ("だいぶ","cukup banyak/lumayan","だいぶ上手になった。","Daibu jouzu ni natta.","Lumayan sudah mahir."),
    ("だんだん","semakin lama semakin","だんだん寒くなってきた。","Dandan samuku natte kita.","Semakin lama semakin dingin."),
    ("ちがい","perbedaan","二つの意見の違いを説明する。","Futatsu no iken no chigai o setsumei suru.","Menjelaskan perbedaan dua pendapat."),
    ("ちゃんと","dengan benar/sungguh-sungguh","ちゃんと宿題をした。","Chanto shukudai o shita.","Mengerjakan PR dengan benar."),
    ("ちょくせつ","langsung","直接話し合いました。","Chokusetsu hanashiaimashita.","Berdiskusi secara langsung."),
    ("ちょっと","sebentar/sedikit","ちょっと待ってください。","Chotto matte kudasai.","Tolong tunggu sebentar."),
    ("ついに","akhirnya","ついに目標を達成した。","Tsui ni mokuhyou o tassei shita.","Akhirnya mencapai tujuan."),
    ("つうきん","perjalanan kerja/komuter","毎日電車で通勤する。","Mainichi densha de tsuukin suru.","Komuter dengan kereta setiap hari."),
    ("つかれる","kelelahan","仕事で疲れた。","Shigoto de tsukareta.","Lelah karena pekerjaan."),
    ("つたえる","menyampaikan","大切なことを伝えたい。","Taisetsu na koto o tsutaetai.","Ingin menyampaikan hal penting."),
    ("つづける","melanjutkan/meneruskan","毎日練習を続ける。","Mainichi renshuu o tsuzukeru.","Melanjutkan latihan setiap hari."),
    ("つまり","artinya/dengan kata lain","つまり、無理だということです。","Tsumari, muri da to iu koto desu.","Artinya itu tidak mungkin."),
    ("てつだう","membantu/menolong","引越しを手伝いました。","Hikkoshi o tetsudaimashita.","Membantu pindahan."),
    ("できるだけ","sebisa mungkin","できるだけ早く来てください。","Dekiru dake hayaku kite kudasai.","Tolong datang secepat mungkin."),
    ("とうとう","akhirnya/pada akhirnya","とうとう雨が降ってきた。","Toutou ame ga futte kita.","Akhirnya hujan turun juga."),
    ("とくい","pandai/mahir","数学が得意です。","Suugaku ga tokui desu.","Pandai matematika."),
    ("とくに","terutama/khususnya","特に数学が得意です。","Toku ni suugaku ga tokui desu.","Terutama pandai matematika."),
    ("ところが","namun ternyata","行こうとしたところが雨が降った。","Ikou to shita tokoro ga ame ga futta.","Saat akan pergi ternyata hujan."),
    ("ところで","ngomong-ngomong","ところで、昨日何をしましたか。","Tokoro de, kinou nani o shimashita ka.","Ngomong-ngomong kemarin kamu ngapain?"),
    ("とちゅう","di tengah jalan/proses","途中で雨が降ってきた。","Tochuu de ame ga futte kita.","Di tengah jalan hujan turun."),
    ("とにかく","pokoknya/bagaimanapun","とにかく頑張ろう。","Tonikaku ganbarou.","Pokoknya mari berjuang."),
    ("どうせ","toh/bagaimanapun juga","どうせ無理だと思った。","Douse muri da to omotta.","Bagaimanapun juga kupikir tidak mungkin."),
    ("どうぞ","silakan","どうぞ座ってください。","Douzo suwatte kudasai.","Silakan duduk."),
    ("どうやら","sepertinya/tampaknya","どうやら雨が降るようだ。","Douyara ame ga furu you da.","Sepertinya akan hujan."),
    ("なかなか〜ない","susah untuk","なかなか覚えられない。","Nakanaka oboerarenai.","Susah untuk diingat."),
    ("なぜ","mengapa","なぜ遅刻したのですか。","Naze chikoku shita no desuka.","Mengapa terlambat?"),
    ("なるほど","memang/oh begitu","なるほど、そういうことか。","Naruhodo, sou iu koto ka.","Oh begitu ya."),
    ("なるべく","sebisa mungkin","なるべく早く来てください。","Narubeku hayaku kite kudasai.","Tolong datang secepat mungkin."),
    ("にがて","tidak pandai/lemah","数学が苦手です。","Suugaku ga nigate desu.","Tidak pandai matematika."),
    ("にっき","buku harian","毎日日記をつけています。","Mainichi nikki o tsukete imasu.","Menulis buku harian setiap hari."),
    ("にもかかわらず","meskipun/walaupun","雨にもかかわらず出かけた。","Ame ni mo kakawarazu dekaketa.","Meskipun hujan tetap pergi keluar."),
    ("ねっしん","semangat/antusias","熱心に勉強する学生だ。","Nesshin ni benkyou suru gakusei da.","Pelajar yang belajar dengan antusias."),
    ("ねぼう","bangun kesiangan","今日は寝坊してしまった。","Kyou wa nebou shite shimatta.","Hari ini bangun kesiangan."),
    ("のこる","tersisa/tertinggal","食べ物が残ってしまった。","Tabemono ga nokotte shimatta.","Makanan masih tersisa."),
    ("はずだ","seharusnya","もう来るはずです。","Mou kuru hazu desu.","Seharusnya sudah datang."),
    ("はじめて","pertama kali","日本に初めて来た。","Nihon ni hajimete kita.","Pertama kali datang ke Jepang."),
    ("はっきり","dengan jelas/tegas","はっきり言ってください。","Hakkiri itte kudasai.","Tolong bicara dengan jelas."),
    ("はなしあう","berdiskusi","問題について話し合った。","Mondai ni tsuite hanashiatta.","Berdiskusi tentang masalah."),
    ("はんたい","kebalikan/menentang","計画に反対する人がいる。","Keikaku ni hantai suru hito ga iru.","Ada orang yang menentang rencana."),
    ("ばかり","hanya/baru saja","食べてばかりいる。","Tabete bakari iru.","Hanya makan saja terus."),
    ("ひさしぶり","lama tidak bertemu","久しぶりですね。","Hisashiburi desu ne.","Lama tidak bertemu ya."),
    ("ひつよう","perlu/diperlukan","パスポートが必要です。","Pasupooto ga hitsuyou desu.","Paspor diperlukan."),
    ("ふつう","biasa/normal","普通に生活しています。","Futsuu ni seikatsu shite imasu.","Menjalani kehidupan yang normal."),
    ("ぶんか","budaya","日本の文化に興味がある。","Nihon no bunka ni kyoumi ga aru.","Tertarik dengan budaya Jepang."),
    ("へんか","perubahan","気候の変化が激しい。","Kikou no henka ga hageshii.","Perubahan iklim sangat drastis."),
    ("べんきょう","belajar","毎日勉強します。","Mainichi benkyou shimasu.","Belajar setiap hari."),
    ("べんり","praktis/nyaman","スマホはとても便利です。","Sumaho wa totemo benri desu.","Smartphone sangat praktis."),
    ("ほうほう","cara/metode","効率的な方法を探す。","Kouritsutek na houhou o sagasu.","Mencari cara yang efisien."),
    ("まあまあ","lumayan/biasa saja","まあまあです。","Maa maa desu.","Lumayan."),
    ("まず","pertama-tama","まず手を洗ってください。","Mazu te o aratte kudasai.","Pertama-tama cuci tangan."),
    ("まにあう","tepat waktu/keburu","電車に間に合った。","Densha ni ma ni atta.","Keburu keretanya."),
    ("まもる","menjaga/melindungi","環境を守る必要がある。","Kankyou o mamoru hitsuyou ga aru.","Perlu menjaga lingkungan."),
    ("まるで","seolah-olah/bagaikan","まるで夢のようです。","Marude yume no you desu.","Seolah-olah seperti mimpi."),
    ("みとめる","mengakui/menerima","失敗を認める勇気がある。","Shippai o mitomeru yuuki ga aru.","Punya keberanian untuk mengakui kegagalan."),
    ("むかえる","menjemput/menyambut","友達を空港で迎えた。","Tomodachi o kuukou de mukaeta.","Menjemput teman di bandara."),
    ("むしろ","lebih baik/justru","むしろ一人の方が楽だ。","Mushiro hitori no hou ga raku da.","Justru lebih nyaman sendirian."),
    ("めんどう","repot/merepotkan","面倒なことを頼んでしまった。","Mendou na koto o tanonde shimatta.","Meminta hal yang merepotkan."),
    ("もうしこむ","mendaftar/mengajukan","コースに申し込みました。","Koosu ni moushikomimashita.","Mendaftar ke kursus."),
    ("もしかしたら","mungkin saja","もしかしたら来ないかもしれない。","Moshikashitara konai kamo shirenai.","Mungkin saja tidak datang."),
    ("もちろん","tentu saja","もちろんいいですよ。","Mochiron ii desu yo.","Tentu saja boleh."),
    ("もったいない","sayang/mubazir","食べ物を捨てるのはもったいない。","Tabemono o suteru no wa mottainai.","Sayang membuang makanan."),
    ("やくにたつ","berguna/bermanfaat","この知識はきっと役に立つ。","Kono chishiki wa kitto yaku ni tatsu.","Pengetahuan ini pasti berguna."),
    ("やっぱり","ternyata/memang","やっぱり日本語は難しい。","Yappari nihongo wa muzukashii.","Ternyata bahasa Jepang memang sulit."),
    ("やはり","ternyata/seperti yang kuduga","やはり難しかった。","Yahari muzukashikatta.","Ternyata memang sulit."),
    ("ゆっくり","pelan-pelan/santai","ゆっくり話してください。","Yukkuri hanashite kudasai.","Tolong bicara pelan-pelan."),
    ("ようやく","akhirnya/baru saja bisa","ようやく終わった。","Youyaku owatta.","Akhirnya selesai."),
    ("よく","sering/dengan baik","よく分かりました。","Yoku wakarimashita.","Sudah betul-betul mengerti."),
    ("よてい","jadwal/rencana","明日の予定は何ですか。","Ashita no yotei wa nan desuka.","Apa rencanamu besok?"),
    ("らしい","sepertinya/katanya","雨が降るらしい。","Ame ga furu rashii.","Sepertinya akan hujan."),
    ("りかい","pemahaman","相手の気持ちを理解する。","Aite no kimochi o rikai suru.","Memahami perasaan orang lain."),
    ("りゆう","alasan/sebab","遅刻した理由を説明した。","Chikoku shita riyuu o setsumei shita.","Menjelaskan alasan terlambat."),
    ("れんしゅう","latihan/praktik","毎日練習することが大切だ。","Mainichi renshuu suru koto ga taisetsu da.","Berlatih setiap hari itu penting."),
    ("れんらく","kontak/pemberitahuan","明日連絡します。","Ashita renraku shimasu.","Saya akan menghubungi besok."),
    ("わかれる","berpisah","駅で友達と別れた。","Eki de tomodachi to wakareta.","Berpisah dengan teman di stasiun."),
    ("わざと","dengan sengaja","わざとじゃないです。","Wazato ja nai desu.","Bukan dengan sengaja."),
    ("わざわざ","sengaja/repot-repot","わざわざ来てくれてありがとう。","Wazawaza kite kurete arigatou.","Terima kasih sudah repot-repot datang."),
    ("わりあい","relatif/cukup","わりあい早く終わった。","Wariai hayaku owatta.","Selesai relatif cepat."),
    ("〜てあげる","melakukan untuk orang lain","荷物を持ってあげました。","Nimotsu o motte agemashita.","Membawakan barang untuk orang itu."),
    ("〜てもらう","meminta orang melakukan","説明してもらった。","Setsumei shite moratta.","Sudah dimintai penjelasan."),
    ("〜てくれる","orang melakukan untuk saya","手伝ってくれた。","Tetsudatte kureta.","Dibantu olehnya."),
    ("〜ておく","melakukan terlebih dahulu","準備しておいた。","Junbi shite oita.","Sudah bersiap terlebih dahulu."),
    ("〜てしまう","melakukan sampai selesai/menyesal","食べてしまった。","Tabete shimatta.","Sudah termakan semua."),
    ("〜てみる","mencoba melakukan","食べてみてください。","Tabete mite kudasai.","Coba dimakan."),
    ("〜ながら","sambil melakukan","音楽を聴きながら勉強した。","Ongaku o kiki nagara benkyou shita.","Belajar sambil mendengarkan musik."),
    ("〜ために","demi/untuk tujuan","健康のために運動する。","Kenkou no tame ni undou suru.","Olahraga demi kesehatan."),
    ("〜ように","agar supaya","忘れないようにメモした。","Wasurenai you ni memo shita.","Mencatat agar tidak lupa."),
    ("〜かもしれない","mungkin/bisa jadi","明日雨かもしれない。","Ashita ame kamo shirenai.","Besok mungkin hujan."),
    ("〜はずだ","seharusnya","もう着くはずです。","Mou tsuku hazu desu.","Seharusnya sudah tiba."),
    ("〜はずがない","tidak mungkin","彼が嘘をつくはずがない。","Kare ga uso o tsuku hazu ga nai.","Tidak mungkin dia berbohong."),
    ("〜ばよかった","seandainya saja","もっと勉強すればよかった。","Motto benkyou sureba yokatta.","Seandainya saja belajar lebih giat."),
    ("〜でしょう","mungkin/sepertinya","明日は晴れでしょう。","Ashita wa hare deshou.","Besok mungkin cerah."),
    ("〜そうだ","kelihatannya akan","雨が降りそうです。","Ame ga furi sou desu.","Kelihatannya akan hujan."),
    ("〜すぎる","terlalu","食べすぎてしまった。","Tabesugite shimatta.","Terlalu banyak makan."),
    ("〜やすい","mudah untuk","この本は読みやすい。","Kono hon wa yomiyasui.","Buku ini mudah dibaca."),
    ("〜にくい","sulit untuk","この漢字は書きにくい。","Kono kanji wa kaki nikui.","Kanji ini sulit ditulis."),
    ("〜てから","setelah melakukan","宿題をしてから遊ぶ。","Shukudai o shite kara asobu.","Bermain setelah mengerjakan PR."),
    ("〜たあとで","setelah","食べた後で散歩した。","Tabeta ato de sanpo shita.","Jalan-jalan setelah makan."),
    ("〜前に","sebelum","寝る前に歯を磨く。","Neru mae ni ha o migaku.","Menggosok gigi sebelum tidur."),
    ("〜まで","sampai/hingga","6時まで働いた。","Rokuji made hataraita.","Bekerja sampai jam 6."),
    ("〜あいだ","selama/sementara","雨のあいだ家にいた。","Ame no aida ie ni ita.","Berada di rumah selama hujan."),
    ("〜によると","menurut","天気予報によると明日は晴れだ。","Tenki yohou ni yoru to ashita wa hare da.","Menurut prakiraan cuaca besok cerah."),
    ("〜について","tentang/mengenai","日本について話した。","Nihon ni tsuite hanashita.","Berbicara tentang Jepang."),
    ("〜のに","padahal/meskipun","頑張ったのに失敗した。","Ganbatta no ni shippai shita.","Padahal sudah berusaha tapi gagal."),
    ("〜ても","meskipun/walaupun","雨でも行きます。","Ame demo ikimasu.","Meskipun hujan tetap pergi."),
    ("〜し","dan juga/selain itu","安いし、美味しいし最高だ。","Yasui shi, oishii shi saikou da.","Murah dan enak terbaik."),
    ("〜ほど〜ない","tidak se~ seperti","思ったほど難しくなかった。","Omotta hodo muzukashiku nakatta.","Tidak sesulit yang dibayangkan."),
    ("〜たり〜たりする","melakukan ini itu bergantian","読んだり書いたりします。","Yondari kaitari shimasu.","Membaca atau menulis dsb."),
    ("〜ばかりでなく","tidak hanya~ tapi juga","日本語ばかりでなく英語も話せる。","Nihongo bakari de naku eigo mo hanaseru.","Tidak hanya bahasa Jepang bisa bahasa Inggris juga."),
    ("〜おかげで","berkat","先生のおかげで合格できた。","Sensei no okage de goukaku dekita.","Berkat guru bisa lulus."),
    ("〜せいで","gara-gara","風邪のせいで休んだ。","Kaze no sei de yasunda.","Gara-gara flu absen."),
    ("あいさつ","salam/sapaan","毎朝あいさつをします。","Maiasa aisatsu o shimasu.","Memberi salam setiap pagi."),
    ("いがい","selain/kecuali","これ以外に方法がない。","Kore igai ni houhou ga nai.","Tidak ada cara selain ini."),
    ("いっぽう","sementara itu/di sisi lain","勉強する一方で遊んでいる。","Benkyou suru ippou de asonde iru.","Di sisi lain belajar sambil bermain."),
    ("うりば","bagian penjualan","食品売り場はどこですか。","Shokuhin uriba wa doko desuka.","Di mana bagian makanan?"),
    ("えいきょう","pengaruh","天気が気分に影響する。","Tenki ga kibun ni eikyou suru.","Cuaca mempengaruhi suasana hati."),
    ("えんりょ","sungkan/menahan diri","遠慮しないでください。","Enryo shinaide kudasai.","Jangan sungkan."),
    ("おかげ","berkat/karena","あなたのおかげで助かった。","Anata no okage de tasukatta.","Terselamatkan berkat kamu."),
    ("おこなう","melaksanakan","式典を行います。","Shikiten o okonaimasu.","Melaksanakan upacara."),
    ("おそらく","mungkin/kemungkinan besar","おそらく明日は雨でしょう。","Osoraku ashita wa ame deshou.","Kemungkinan besar besok akan hujan."),
    ("おどろく","terkejut","その知らせに驚いた。","Sono shirase ni odoroita.","Terkejut dengan berita itu."),
    ("おもいきって","dengan berani","思い切って挑戦した。","Omoikitte chousen shita.","Berani mencoba dengan tekad bulat."),
    ("きっと","pasti/tentu","きっとうまくいくよ。","Kitto umaku iku yo.","Pasti berhasil."),
    ("くれる","memberikan (kepada saya)","友達がプレゼントをくれた。","Tomodachi ga purezento o kureta.","Teman memberi saya hadiah."),
    ("こんなに","sebegini/seperti ini","こんなに難しいとは思わなかった。","Konna ni muzukashii to wa omowanakatta.","Tidak menyangka sesulit ini."),
    ("さっき","tadi/barusan","さっき電話がありました。","Sakki denwa ga arimashita.","Tadi ada telepon."),
    ("さいのう","bakat","彼女は才能がある。","Kanojo wa sainou ga aru.","Dia punya bakat."),
    ("しかた","cara","やり方を教えてください。","Yarikata o oshiete kudasai.","Tolong ajarkan caranya."),
    ("たまに","kadang-kadang","たまに映画を見ます。","Tama ni eiga o mimasu.","Kadang-kadang menonton film."),
    ("ねえ","hei/eh (menarik perhatian)","ねえ、聞いてください。","Nee, kiite kudasai.","Hei tolong dengarkan."),
    ("ふと","tiba-tiba/tanpa disengaja","ふと空を見上げた。","Futo sora o miageta.","Tiba-tiba menatap langit."),
    ("もし〜たら","jika/seandainya","もし雨が降ったらどうしますか。","Moshi ame ga futtara dou shimasu ka.","Jika hujan apa yang akan kamu lakukan?"),
    ("わりに","relatif/dibandingkan","値段のわりに美味しい。","Nedan no wari ni oishii.","Relatif enak dibanding harganya."),
    ("きかい","mesin/kesempatan","機械が壊れた。","Kikai ga kowareta.","Mesinnya rusak."),
    ("ふべん","tidak nyaman","不便な場所に住んでいる。","Fuben na basho ni sunde iru.","Tinggal di tempat yang tidak nyaman."),
    ("あんぜん","aman","安全な道を歩く。","Anzen na michi o aruku.","Berjalan di jalan yang aman."),
    ("しょうじき","jujur","正直に話してください。","Shoujiki ni hanashite kudasai.","Tolong bicara jujur."),
    ("まじめ","serius/tekun","真面目に勉強する。","Majime ni benkyou suru.","Belajar dengan serius."),
    ("ちょうど","tepat/pas","ちょうどいい大きさです。","Choudo ii ookisa desu.","Ukurannya pas."),
    ("だいじょうぶ","tidak apa-apa","大丈夫ですか。","Daijoubu desuka.","Apa tidak apa-apa?"),
    ("ていねい","sopan/teliti","丁寧に説明した。","Teinei ni setsumei shita.","Menjelaskan dengan teliti."),
    ("とくべつ","istimewa/khusus","今日は特別な日です。","Kyou wa tokubetsu na hi desu.","Hari ini hari istimewa."),
    ("ひっこし","pindah rumah","来月引越しします。","Raigetsu hikkoshi shimasu.","Bulan depan pindah rumah."),
    ("しゅうかん","kebiasaan/minggu","良い習慣を作る。","Yoi shuukan o tsukuru.","Membuat kebiasaan yang baik."),
    ("せんもん","spesialisasi/jurusan","専門は何ですか。","Senmon wa nan desuka.","Spesialisasimu apa?"),
    ("そつぎょう","kelulusan","来年卒業します。","Rainen sotsugyou shimasu.","Tahun depan lulus."),
    ("にゅうがく","masuk sekolah","来月入学します。","Raigetsu nyuugaku shimasu.","Bulan depan masuk sekolah."),
    ("ちゅうもん","pemesanan","料理を注文した。","Ryouri o chuumon shita.","Memesan masakan."),
    ("よやく","reservasi/janji","ホテルを予約した。","Hoteru o yoyaku shita.","Memesan hotel."),
    ("しょうかい","perkenalan","自己紹介をした。","Jiko shoukai o shita.","Melakukan perkenalan diri."),
    ("せつめい","penjelasan","説明が分かりやすい。","Setsumei ga wakariyasui.","Penjelasannya mudah dipahami."),
    ("はなしかた","cara berbicara","話し方が丁寧です。","Hanashikata ga teinei desu.","Cara berbicaranya sopan."),
    ("きもち","perasaan","気持ちを伝えたい。","Kimochi o tsutaetai.","Ingin menyampaikan perasaan."),
    ("きぶん","suasana hati","今日は気分がいい。","Kyou wa kibun ga ii.","Suasana hati hari ini baik."),
    ("いけん","pendapat","意見を言ってください。","Iken o itte kudasai.","Tolong sampaikan pendapatmu."),
    ("かんがえ","pikiran/ide","いい考えが浮かんだ。","Ii kangae ga ukanda.","Muncul ide yang bagus."),
    ("もくひょう","tujuan/target","目標を立てた。","Mokuhyou o tateta.","Menetapkan target."),
    ("ゆめ","mimpi","大きな夢を持っている。","Ookina yume o motte iru.","Punya mimpi yang besar."),
    ("きぼう","harapan","希望を持って進む。","Kibou o motte susumu.","Maju dengan penuh harapan."),
    ("もんだい","masalah/soal","問題を解決した。","Mondai o kaiketsu shita.","Memecahkan masalah."),
    ("こたえ","jawaban","正しい答えを選ぶ。","Tadashii kotae o erabu.","Memilih jawaban yang benar."),
    ("しつもん","pertanyaan","質問があります。","Shitsumon ga arimasu.","Ada pertanyaan."),
    ("せいせき","nilai/prestasi","成績が上がった。","Seiseki ga agatta.","Nilai naik."),
    ("しけん","ujian","明日試験があります。","Ashita shiken ga arimasu.","Besok ada ujian."),
    ("さくぶん","karangan/esai","作文を書いた。","Sakubun o kaita.","Menulis karangan."),
    ("ほんやく","terjemahan","文章を翻訳した。","Bunshou o hon-yaku shita.","Menerjemahkan kalimat."),
    ("じしょ","kamus","辞書で調べた。","Jisho de shirabeta.","Mencari di kamus."),
    ("ノート","buku catatan","ノートに書いた。","Nooto ni kaita.","Menulis di buku catatan."),
    ("きょうかしょ","buku pelajaran","教科書を開いてください。","Kyoukasho o aite kudasai.","Tolong buka buku pelajaran."),
    ("じゅぎょう","pelajaran/kelas","授業に遅刻した。","Jugyou ni chikoku shita.","Terlambat masuk kelas."),
    ("やすみ","hari libur/istirahat","明日は休みです。","Ashita wa yasumi desu.","Besok hari libur."),
    ("しゅくだい","pekerjaan rumah (PR)","宿題を忘れた。","Shukudai o wasureta.","Lupa mengerjakan PR."),
    ("ぶかつ","kegiatan ekstrakurikuler","部活が忙しい。","Bukatsu ga isogashii.","Ekstrakurikuler sibuk."),
    ("かいしゃ","perusahaan","会社に就職した。","Kaisha ni shuushoku shita.","Mendapat pekerjaan di perusahaan."),
    ("しごと","pekerjaan","仕事が忙しい。","Shigoto ga isogashii.","Pekerjaan sedang sibuk."),
    ("きゅうりょう","gaji","給料をもらった。","Kyuuryou o moratta.","Mendapat gaji."),
    ("かいぎ","rapat","会議に出席した。","Kaigi ni shusseki shita.","Menghadiri rapat."),
    ("しゅっちょう","perjalanan dinas","出張で大阪に行った。","Shucchou de Oosaka ni itta.","Pergi ke Osaka untuk perjalanan dinas."),
    ("やちん","uang sewa","家賃を払った。","Yachin o haratta.","Membayar uang sewa."),
    ("こうつう","transportasi","交通費が高い。","Koutsuu-hi ga takai.","Biaya transportasi mahal."),
    ("でんしゃ","kereta listrik","電車で行きます。","Densha de ikimasu.","Pergi naik kereta."),
    ("バス","bus","バスに乗った。","Basu ni notta.","Naik bus."),
    ("タクシー","taksi","タクシーを呼んだ。","Takushii o yonda.","Memanggil taksi."),
    ("じてんしゃ","sepeda","自転車で通学する。","Jitensha de tsuugaku suru.","Pergi sekolah naik sepeda."),
    ("くるま","mobil","車を運転した。","Kuruma o unten shita.","Menyetir mobil."),
    ("ひこうき","pesawat","飛行機に乗った。","Hikouki ni notta.","Naik pesawat."),
    ("ふね","kapal","船で旅行した。","Fune de ryokou shita.","Berwisata naik kapal."),
    ("みち","jalan","この道はどこに続いていますか。","Kono michi wa doko ni tsuzuite imasu ka.","Jalan ini menuju ke mana?"),
    ("こうさてん","persimpangan","交差点で曲がってください。","Kousaten de magatte kudasai.","Tolong belok di persimpangan."),
    ("しんごう","lampu lalu lintas","信号が赤になった。","Shingou ga aka ni natta.","Lampu lalu lintas menjadi merah."),
    ("ちず","peta","地図を見ながら歩いた。","Chizu o minagara aruita.","Berjalan sambil melihat peta."),
    ("じゅうしょ","alamat","住所を教えてください。","Juusho o oshiete kudasai.","Tolong beritahu alamatnya."),
    ("でんわ","telepon","電話をかけた。","Denwa o kaketa.","Menelepon."),
    ("メール","email","メールを送った。","Meeru o okutta.","Mengirim email."),
    ("インターネット","internet","インターネットで調べた。","Intaanetto de shirabeta.","Mencari di internet."),
    ("スマホ","smartphone","スマホをよく使う。","Sumaho o yoku tsukau.","Sering menggunakan smartphone."),
    ("パソコン","komputer","パソコンで仕事をする。","Pasokon de shigoto o suru.","Bekerja menggunakan komputer."),
    ("テレビ","televisi","テレビを見た。","Terebi o mita.","Menonton TV."),
    ("ラジオ","radio","ラジオを聴いた。","Rajio o kiita.","Mendengarkan radio."),
    ("しんぶん","koran","新聞を読んだ。","Shinbun o yonda.","Membaca koran."),
    ("ざっし","majalah","雑誌を買った。","Zasshi o katta.","Membeli majalah."),
    ("えいが","film","映画を見に行った。","Eiga o mi ni itta.","Pergi menonton film."),
    ("おんがく","musik","音楽を聴くのが好きです。","Ongaku o kiku no ga suki desu.","Suka mendengarkan musik."),
    ("スポーツ","olahraga","スポーツが好きです。","Supootsu ga suki desu.","Suka olahraga."),
    ("やきゅう","baseball","野球の試合を見た。","Yakyuu no shiai o mita.","Menonton pertandingan baseball."),
    ("サッカー","sepak bola","サッカーをした。","Sakkaa o shita.","Bermain sepak bola."),
    ("テニス","tenis","テニスが得意です。","Tenisu ga tokui desu.","Pandai bermain tenis."),
    ("りょうり","masakan/memasak","料理を作るのが好きです。","Ryouri o tsukuru no ga suki desu.","Suka membuat masakan."),
    ("かいもの","belanja","買い物に行った。","Kaimono ni itta.","Pergi belanja."),
    ("りょこう","perjalanan wisata","旅行が好きです。","Ryokou ga suki desu.","Suka berwisata."),
    ("しゃしん","foto","写真を撮った。","Shashin o totta.","Mengambil foto."),
    ("にわ","taman/halaman","庭に花を植えた。","Niwa ni hana o ueta.","Menanam bunga di taman."),
    ("てんき","cuaca","天気がいいですね。","Tenki ga ii desu ne.","Cuacanya bagus ya."),
    ("きせつ","musim","好きな季節は秋です。","Sukina kisetsu wa aki desu.","Musim favoritku adalah musim gugur."),
    ("きおん","suhu udara","気温が下がった。","Kion ga sagatta.","Suhu udara turun."),
    ("かぜ","angin/flu","風邪をひいた。","Kaze o hiita.","Kena flu."),
    ("くもり","berawan","今日は曇りです。","Kyou wa kumori desu.","Hari ini berawan."),
    ("ゆき","salju","雪が降った。","Yuki ga futta.","Salju turun."),
    ("たいふう","topan","台風が来た。","Taifuu ga kita.","Topan datang."),
    ("じしん","gempa bumi","地震が起きた。","Jishin ga okita.","Gempa bumi terjadi."),
    ("ほけん","asuransi/kesehatan","健康保険に入っている。","Kenkou hoken ni haitte iru.","Memiliki asuransi kesehatan."),
    ("びょうき","sakit/penyakit","病気になった。","Byouki ni natta.","Jatuh sakit."),
    ("くすり","obat","薬を飲んだ。","Kusuri o nonda.","Minum obat."),
    ("びょういん","rumah sakit","病院に行った。","Byouin ni itta.","Pergi ke rumah sakit."),
    ("いしゃ","dokter","医者に診てもらった。","Isha ni mite moratta.","Diperiksa dokter."),
    ("かんごし","perawat","看護師に注射された。","Kangoshi ni chuusha sareta.","Disuntik oleh perawat."),
    ("けが","luka/cedera","怪我をした。","Kega o shita.","Terluka."),
    ("ねつ","demam","熱が出た。","Netsu ga deta.","Demam muncul."),
    ("せき","batuk","咳が止まらない。","Seki ga tomaranai.","Batuk tidak berhenti."),
    ("いたい","sakit/nyeri","頭が痛い。","Atama ga itai.","Kepala sakit."),
    ("しょくじ","makan/makanan","食事をした。","Shokuji o shita.","Makan."),
    ("あさごはん","sarapan","朝ごはんを食べた。","Asagohan o tabeta.","Makan sarapan."),
    ("ひるごはん","makan siang","昼ごはんを食べた。","Hirugohan o tabeta.","Makan siang."),
    ("ばんごはん","makan malam","晩ごはんを食べた。","Bangohan o tabeta.","Makan malam."),
    ("やさい","sayuran","野菜をたくさん食べる。","Yasai o takusan taberu.","Makan banyak sayuran."),
    ("くだもの","buah","果物が好きです。","Kudamono ga suki desu.","Suka buah."),
    ("さかな","ikan","魚を食べた。","Sakana o tabeta.","Makan ikan."),
    ("にく","daging","肉が好きです。","Niku ga suki desu.","Suka daging."),
    ("ごはん","nasi/makanan","ご飯を食べましょう。","Gohan o tabemashou.","Ayo makan."),
    ("パン","roti","パンを食べた。","Pan o tabeta.","Makan roti."),
    ("コーヒー","kopi","コーヒーを飲んだ。","Koohii o nonda.","Minum kopi."),
    ("おちゃ","teh","お茶を飲んだ。","Ocha o nonda.","Minum teh."),
    ("みず","air","水を飲んだ。","Mizu o nonda.","Minum air."),
    ("ジュース","jus","ジュースを飲んだ。","Juusu o nonda.","Minum jus."),
    ("ビール","bir","ビールを飲んだ。","Biiru o nonda.","Minum bir."),
    ("スープ","sup","スープを飲んだ。","Suupu o nonda.","Minum sup."),
    ("ラーメン","ramen","ラーメンが好きです。","Raamen ga suki desu.","Suka ramen."),
    ("すし","sushi","寿司を食べた。","Sushi o tabeta.","Makan sushi."),
    ("てんぷら","tempura","天ぷらが美味しい。","Tenpura ga oishii.","Tempura enak."),
    ("そば","soba","蕎麦を食べた。","Soba o tabeta.","Makan soba."),
    ("うどん","udon","うどんが好きです。","Udon ga suki desu.","Suka udon."),
    ("カレー","kari","カレーを作った。","Karee o tsukutta.","Membuat kari."),
    ("いえ","rumah","家に帰った。","Ie ni kaetta.","Pulang ke rumah."),
    ("アパート","apartemen","アパートに住んでいる。","Apaato ni sunde iru.","Tinggal di apartemen."),
    ("マンション","kondominium","マンションを買った。","Manshon o katta.","Membeli kondominium."),
    ("へや","kamar","部屋を掃除した。","Heya o souji shita.","Membersihkan kamar."),
    ("だいどころ","dapur","台所で料理した。","Daidokoro de ryouri shita.","Memasak di dapur."),
    ("トイレ","toilet","トイレに行った。","Toire ni itta.","Pergi ke toilet."),
    ("おふろ","kamar mandi/bak mandi","お風呂に入った。","Ofuro ni haitta.","Mandi."),
    ("ふとん","kasur/selimut","布団を敷いた。","Futon o shiita.","Menggelar kasur."),
    ("まど","jendela","窓を開けた。","Mado o aketa.","Membuka jendela."),
    ("でぐち","pintu keluar","出口はどこですか。","Deguchi wa doko desuka.","Di mana pintu keluarnya?"),
    ("いりぐち","pintu masuk","入口から入ってください。","Iriguchi kara haitte kudasai.","Tolong masuk dari pintu masuk."),
    ("エレベーター","lift/elevator","エレベーターで上がった。","Erebeetaa de agatta.","Naik dengan lift."),
    ("かいだん","tangga","階段を上がった。","Kaidan o agatta.","Naik tangga."),
]

TIPS = [
    "Kanji N4 banyak berhubungan dengan kehidupan sehari-hari — coba gunakan dalam percakapan!",
    "Pola kalimat 〜てあげる/もらう/くれる sangat sering dipakai. Hafalkan ketiganya!",
    "Coba tonton drama Jepang — banyak kosakata N4 muncul dalam percakapan natural.",
    "Belajar kanji N4 bersama on-yomi dan kun-yomi-nya sekaligus lebih efektif.",
    "Tulis 3 kalimat menggunakan kanji hari ini — praktek langsung memperkuat ingatan!",
    "Spaced repetition adalah kunci. Review materi lama sambil belajar yang baru.",
    "Baca teks bahasa Jepang sederhana setiap hari — manga anak-anak cocok untuk N4.",
    "Konsistensi mengalahkan intensitas. 15 menit setiap hari lebih baik dari 3 jam seminggu.",
    "Jangan lewatkan pola 〜てしまう、〜ておく、〜てみる — ini kunci level N4!",
    "Catat kosakata baru dalam kalimat lengkap, bukan hanya kata tunggal.",
    "Coba gunakan kosakata hari ini dalam percakapan nyata atau tulisan diary.",
    "がんばれば必ずできる！ Kalau berusaha pasti bisa!",
]

# ============================================================
# KONFIGURASI JADWAL
# ============================================================
TOTAL_KANJI     = len(KANJI)
TOTAL_VOCAB     = len(VOCAB)
KANJI_PER_HARI  = 6   # 300 kanji ÷ 3 = 100 hari
VOCAB_PER_HARI  = 7   # 700 vocab ÷ 5 = 140 hari → selesai ~sama
TOTAL_HARI      = max(
    -(-TOTAL_KANJI // KANJI_PER_HARI),
    -(-TOTAL_VOCAB // VOCAB_PER_HARI)
)

def kirim_pesan(text):
    url  = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    data = json.dumps({"chat_id": CHAT_ID, "text": text, "parse_mode": "Markdown"}).encode()
    req  = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    urllib.request.urlopen(req)

def get_hari_ke():
    mulai = datetime(2026, 6, 14)
    today = datetime.now()
    return (today - mulai).days

def pick_hari_ini(hari_ke):
    k_start = (hari_ke * KANJI_PER_HARI) % TOTAL_KANJI
    v_start = (hari_ke * VOCAB_PER_HARI) % TOTAL_VOCAB
    kanji_list = [KANJI[(k_start + i) % TOTAL_KANJI] for i in range(KANJI_PER_HARI)]
    vocab_list = [VOCAB[(v_start + i) % TOTAL_VOCAB] for i in range(VOCAB_PER_HARI)]
    return kanji_list, vocab_list

def cek_selesai(hari_ke):
    kanji_selesai = (hari_ke + 1) * KANJI_PER_HARI >= TOTAL_KANJI
    vocab_selesai = (hari_ke + 1) * VOCAB_PER_HARI >= TOTAL_VOCAB
    return kanji_selesai and vocab_selesai

def buat_pesan_selesai():
    msg = []
    msg.append("🎉 *SELAMAT! SEMUA MATERI N4 SELESAI!* 🎉\n")
    msg.append("━━━━━━━━━━━━━━━━━━━━")
    msg.append("🏆 *PENCAPAIAN LUAR BIASA!*")
    msg.append("━━━━━━━━━━━━━━━━━━━━\n")
    msg.append(f"✅ *{TOTAL_KANJI} Kanji N4* — Semua selesai dipelajari!")
    msg.append(f"✅ *{TOTAL_VOCAB} Kosakata N4* — Semua selesai dipelajari!\n")
    msg.append(f"📅 Diselesaikan dalam *{TOTAL_HARI} hari* belajar konsisten!\n")
    msg.append("Kamu telah menyelesaikan seluruh materi kanji dan")
    msg.append("kosakata JLPT N4. Ini pencapaian yang luar biasa! 🌟\n")
    msg.append("━━━━━━━━━━━━━━━━━━━━")
    msg.append("📚 *LANGKAH SELANJUTNYA:*")
    msg.append("━━━━━━━━━━━━━━━━━━━━\n")
    msg.append("1️⃣ Review ulang dari awal untuk memperkuat ingatan")
    msg.append("2️⃣ Coba latihan soal JLPT N4 resmi")
    msg.append("3️⃣ Ikut ujian JLPT N4 di sesi berikutnya")
    msg.append("4️⃣ Mulai belajar materi N3 untuk naik level!\n")
    msg.append("━━━━━━━━━━━━━━━━━━━━")
    msg.append("🔄 *Bot akan mulai mengirim ulang dari awal besok.*\n")
    msg.append("おめでとうございます！ 🎌🎊")
    return "\n".join(msg)

def buat_pesan_harian(hari_ke, kanji_list, vocab_list):
    today   = datetime.now()
    hari    = ["Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu"][today.weekday()]
    tanggal = today.strftime("%d %B %Y")
    tip     = random.Random(today.year*10000+today.month*100+today.day+99).choice(TIPS)

    k_done = min((hari_ke + 1) * KANJI_PER_HARI, TOTAL_KANJI)
    v_done = min((hari_ke + 1) * VOCAB_PER_HARI, TOTAL_VOCAB)
    k_pct  = int(k_done / TOTAL_KANJI * 100)
    v_pct  = int(v_done / TOTAL_VOCAB * 100)

    baris = []
    baris.append("🌸 *OHAYOU GOZAIMASU!* 🌸")
    baris.append(f"_{hari}, {tanggal}_")
    baris.append(f"Hari ke-*{hari_ke + 1}* dari *{TOTAL_HARI}* hari belajar N4! ✨\n")
    baris.append("━━━━━━━━━━━━━━━━━━━━")
    baris.append(f"📖 *{KANJI_PER_HARI} KANJI N4 HARI INI*")
    baris.append(f"Progress: {k_done}/{TOTAL_KANJI} ({k_pct}%) {'▓' * (k_pct // 10)}{'░' * (10 - k_pct // 10)}")
    baris.append("━━━━━━━━━━━━━━━━━━━━\n")
    for kanji, baca, arti, contoh, romaji, terjemah in kanji_list:
        baris.append(f"🔴 *{kanji}* — {baca}")
        baris.append(f"└ Arti: {arti}")
        baris.append(f"└ Contoh: {contoh}")
        baris.append(f"   ({romaji})")
        baris.append(f"   → {terjemah}\n")
    baris.append("━━━━━━━━━━━━━━━━━━━━")
    baris.append(f"💬 *{VOCAB_PER_HARI} KOSAKATA N4 HARI INI*")
    baris.append(f"Progress: {v_done}/{TOTAL_VOCAB} ({v_pct}%) {'▓' * (v_pct // 10)}{'░' * (10 - v_pct // 10)}")
    baris.append("━━━━━━━━━━━━━━━━━━━━\n")
    for kata, arti, contoh, romaji, terjemah in vocab_list:
        baris.append(f"🔵 *{kata}* — {arti}")
        baris.append(f"└ Contoh: {contoh}")
        baris.append(f"   ({romaji})")
        baris.append(f"   → {terjemah}\n")
    baris.append("━━━━━━━━━━━━━━━━━━━━")
    baris.append("💪 *TIPS N4 HARI INI*")
    baris.append(f"_{tip}_\n")
    baris.append("がんばってください！ 🎌")
    return "\n".join(baris)

# === MAIN ===
hari_ke = get_hari_ke()
log.info(f"Hari ke-{hari_ke + 1} dari {TOTAL_HARI} hari | Kanji: {TOTAL_KANJI} | Vocab: {TOTAL_VOCAB}")

kanji_list, vocab_list = pick_hari_ini(hari_ke)
kirim_pesan(buat_pesan_harian(hari_ke, kanji_list, vocab_list))
log.info("Pesan harian terkirim!")

if cek_selesai(hari_ke):
    kirim_pesan(buat_pesan_selesai())
    log.info("Notifikasi selesai terkirim!")

log.info("Selesai!")
