name: Kirim Kanji Harian

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  kirim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyTelegramBotAPI

      - name: Kirim pesan
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python3 nihonggo_kanji_bot.py
